### PR TITLE
Changed ForeignKeyIndexConvention to update the IsUnique property

### LINKED ISSUE #7254: ModelBuilding: Changing PK of principal type loses the user configured index info on FK property
When user is explicitly configuring the index which is backing FK, if the FK is regenerated then user configuration on the index is lost in the process.
In following example, the index is explicitly set as non-unique. The FK is recreated due to change of PK on principal type. The index becomes unique again.

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to repoduce the issue.

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // Configure model
    modelBuilder.Entity<Account>(etb =>
    {
        etb.HasOne(p => p.Customer)
            .WithOne(p => p.Account)
            .HasForeignKey<Account>(p => p.CustomerId);

        etb.HasIndex(p => p.CustomerId).IsUnique(false);
    });
    modelBuilder.Entity<Customer>(etb =>
    {
        etb.HasKey(p => p.AuditId);
    });
}

public class Account
{
    public int? Id { get; set; }
    public Customer Customer { get; set; }
    public int? CustomerId { get; set; }
}

public class Customer
{
    public int? AuditId { get; set; }
    public int? Id { get; set; }
    public Account Account { get; set; }
}
```

```
var entityType = db.Model.FindEntityType(typeof(Account));
var property = entityType.FindProperty(nameof(Account.CustomerId));
Console.WriteLine(entityType.FindIndex(new List<IProperty> { property}).IsUnique); // outputs true
```

### Further technical details
EF Core version: 1.1.0
Database Provider: SqlServer
Operating system: Win10
IDE: VS 2015U3

### PR DESCRIPTION
**Pull request by tuespetre**
of the ForeignKey when the associated index's uniqueness changes.

Fixes #7254

### CODE REVIEW

File: src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs [hunk 1]
```diff
@@ -202,7 +202,7 @@ bool IIndexUniquenessConvention.Apply(InternalIndexBuilder indexBuilder)
                 foreach (var foreignKey in index.DeclaringEntityType.GetDerivedForeignKeysInclusive()
                     .Where(fk => fk.IsUnique && AreIndexedBy(fk.Properties, fk.IsUnique, index.Properties, existingIndexUniqueness: true)))
                 {
-                    CreateIndex(foreignKey.Properties, foreignKey.IsUnique, foreignKey.DeclaringEntityType.Builder);
+                    foreignKey.IsUnique = false;
```
Comment (ajcvickers) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs]: I don't think this is the correct change. The issue is about the uniqueness on the index being overwritten This instead changes the IsUnique flag on the FK.

Comment (tuespetre) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs]: That makes sense and I will update accordingly; out of curiosity, is there anything else 'linked' to the FK's IsUnique flag I might have missed?

Comment (ajcvickers) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs]: @tuespetre In EF Core metadata, a ForeignKey object defines a relationship, and the IsUnique flag determines whether that relationship is 1:1 or 1:*. EF therefore uses this flag to determine how to handle the relationship in queries, updates, fixup, etc.

Index objects define which indexes should be created in the database when using Migrations. They are currently not reasoned about by non-Migrations code, although this could change.

When a ForeignKey is created an Index will also be created with appropriate configuration for the FK. However, the application may change that Index in some way. This should have no effect on the ForeignKey and will only change how the index is created by Migrations.

Comment (tuespetre) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs]: @ajcvickers thanks! That'll get me thinking about some scenarios. Maybe there also needs to be a test to ensure that the very thing done by this current change does not happen (i.e. test to ensure that changing an index does NOT affect a foreign key.)

Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs]: The correct fix is to remove line 927 from InternalRelationshipBuilder.cs, leftover from before we had the convention:
```
builder?.Metadata.DeclaringEntityType.FindIndex(builder.Metadata.Properties)?.SetIsUnique(unique, configurationSource);
```
And to run `OnForeignKeyUniquenessChanged` conventions in `ReplaceForeignKey` if the FK uniqueness actually changed.

**Comment by rowanmiller** [comment]
@tuespetre are you planning to address the feedback on this PR?

**Comment by tuespetre** [comment]
Yes, sorry for the delay. I hope to get to this soon.

**Comment by tuespetre** [comment]
@ajcvickers I have made changes and rebased. @AndriySvyryd thanks for pointing me in the right direction. By removing that call and then ensuring that the 'added' convention is run for a foreign key during replacement, everything seems to work out.

Note that I did have to change one existing test in order for it to pass -- when a one-to-one is changed to a one-to-many, it still makes sense that the dependents' foreign key stays unique by convention. The existing test had it being no longer unique.

**Comment by AndriySvyryd** [comment]
@tuespetre The test was correct, if the FK uniqueness changes conventions need to update the index uniqueness. To achieve this you need to add code to run `ModelBuilder.Metadata.ConventionDispatcher.OnForeignKeyUniquenessChanged()` in `InternalRelationshipBuilder.ReplaceForeignKey`

**Comment by tuespetre** [comment]
@AndriySvyryd oh geez, yeah I see it now. I got the dependent/principal thing flipped around in my brain holes for some reason. Thanks

**Comment by tuespetre** [comment]
@ajcvickers @AndriySvyryd alright, third time's a charm?

**Comment by AndriySvyryd** [comment]
@tuespetre You are straying in the wrong direction now. `ForeignKeyIndexConvention` doesn't need to be changed, it just needs to be run at the appropriate times.
More specifically currently `InternalRelationshipBuilder.ReplaceForeignKey` invokes `newRelationshipBuilder.IsUnique` with `runConventions: false` to avoid running the conventions prematurely before the relationship is fully configured, but it doesn't call `ModelBuilder.Metadata.ConventionDispatcher.OnForeignKeyUniquenessChanged()` afterwards. The latter is what needs to be added.

**Comment by tuespetre** [comment]
@AndriySvyryd so instead of the change I made [here](https://github.com/aspnet/EntityFramework/pull/7327/files#diff-fafd831e48b8bfe93b1dd176ce8ea02bL2003), add an `else` block that runs the `ModelBuilder.Metadata.ConventionDispatcher.OnForeignKeyUniquenessChanged()`?

**Comment by AndriySvyryd** [comment]
@tuespetre yes, though it would be an `else if` as it should only run if the uniqueness changed

**Comment by tuespetre** [comment]
:up: :date: :hash: :four:

**Comment by AndriySvyryd** [comment]
@tuespetre Looks good if the tests pass 😉

**Comment by tuespetre** [comment]
Well, I guess Travis decided to bail 💀

**Comment by AndriySvyryd** [comment]
@tuespetre StackOverflowException. Run the tests under a debugger to see what's happening.

File: src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs [hunk 2]
```diff
@@ -2000,11 +1999,16 @@ private bool CanInvert(ConfigurationSource? configurationSource)
...
-                    && (newRelationshipBuilder.Metadata != initialRelationship
-                        || existingRelationshipInverted == null))
+                if (newRelationshipBuilder != null)
                 {
-                    newRelationshipBuilder = ModelBuilder.Metadata.ConventionDispatcher.OnForeignKeyAdded(newRelationshipBuilder);
+                    if (newRelationshipBuilder.Metadata != initialRelationship || existingRelationshipInverted == null)
+                    {
+                        newRelationshipBuilder = ModelBuilder.Metadata.ConventionDispatcher.OnForeignKeyAdded(newRelationshipBuilder);
+                    }
+                    else if (oldIsUnique != isUnique)
```
Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs]: Perhaps the problem is here, try instead:
`oldIsUnique != newRelationshipBuilder.Metadata.IsUnique`

**Comment by tuespetre** [comment]
Hmmm. I've been running TestDriven from Visual Studio to avoid the extra wait of the whole build/package process of `build.cmd`, but apparently it doesn't report this kind of error! Guess I need to take note of the total number of tests that ran/passed.

File: src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs (hunk 2 above)
Comment (tuespetre) [inline src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs]: Something is happening in one of the conventions, so the `newRelationshipBuilder` is assigned something new. I see it runs through the `ReuniquifyTempProperties` bit, and each time it comes through it changes to `QRefId1`, `QRefId2`, and so forth.

**Comment by AndriySvyryd** [comment]
@tuespetre Yeah, with TestDriven.net you need to run the tests under the debugger with the option to break when StackOverflowException is thrown, otherwise it just swallows the exception.

File: src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs (hunk 2 above)
Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs]: Oh, perhaps a more accurate test would be
```
Metadata.IsUnique != newRelationshipBuilder.Metadata.IsUnique
```

Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs]: Perhaps a more accurate test would be
```
oldIsUnique != newRelationshipBuilder.Metadata.IsUnique
```

**Comment by AndriySvyryd** [comment]
@tuespetre I found and fixed the bug in  RelationshipDiscoveryConvention that was causing infinite recursion. Thanks for the contribution!

**Comment by tuespetre** [comment]
Oh, nice! Thank you!
