### PR TITLE
Fix to #4739 - UseRowNumberPaging causes NRE in complex queries

### LINKED ISSUE #4739: UseRowNumberPaging causes NRE in complex queries
Repro:
ComplexNavigationsQuerySqlServerTest.Include_with_groupjoin_skip_and_take

Change ComplexNavigationsQuerySqlServerFixture to use row number paging.

Expected:
Instead of offset/fetch, the query generated should use row number paging.

Result:
```
	System.NullReferenceException : Object reference not set to an instance of an object.
	at lambda_method(Closure , ValueBuffer )
	Query\EntityLoadInfo.cs(27,0): at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
	Query\Internal\QueryBuffer.cs(70,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
	Query\ExpressionVisitors\Internal\BufferedEntityShaper`.cs(32,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
	Query\ExpressionVisitors\Internal\BufferedOffsetEntityShaper.cs(26,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedOffsetEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
	Query\QueryMethodProvider.cs(255,0): at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupJoin>d__26`4.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Query\Internal\LinqOperatorProvider.cs(125,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	ComplexNavigationsQueryTestBase.cs(1938,0): at Microsoft.EntityFrameworkCore.FunctionalTests.ComplexNavigationsQueryTestBase`2.Include_with_groupjoin_skip_and_take()
	ComplexNavigationsQuerySqlServerTest.cs(887,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.ComplexNavigationsQuerySqlServerTest.Include_with_groupjoin_skip_and_take()
```

The test throws on this query:
```c#
(from l1 in context.LevelOne
    .Include(e => e.OneToMany_Optional)
    .ThenInclude(e => e.OneToOne_Optional_FK)
join l2 in context.LevelTwo.Include(e => e.OneToOne_Required_PK)
on (int?)l1.Id equals (l2 != null ? l2.Level1_Optional_Id : null) into grouping
where l1.Name != "L1 03"
select new { l1, grouping }).Skip(1).Take(5)
```

### PR DESCRIPTION
**Pull request by maumar**
Fixes #4739 and #5641

Thanks to @sepplK for pointing out where the bug is.

Problem was that during query rewrite for RowNumberPaging, when copying projection elements from the inner query, we were not preserving aliases. Instead were using ColumnExpression (so it would be the projected element in the outer query) even in the alias was explicitly set in the inner SelectExpression. Fix is to try use alias first and only if alias is not set fall-back to using the column name.

### CODE REVIEW

**Comment by maumar** [comment]
@smitpatel @anpete

**Comment by smitpatel** [comment]
yay!

File: src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitor.cs [hunk 1]
```diff
@@ -140,7 +140,7 @@ private Expression VisitSelectExpression(SelectExpression selectExpression)
 
                     if (column != null)
                     {
-                        column = new ColumnExpression(column.Name, column.Property, subQuery);
+                        column = new ColumnExpression(alias?.Alias ?? column.Name, column.Property, subQuery);
```
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitor.cs]: `alias.Alias`

Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitor.cs]: on line 149, make `alias?.Alias`

**Comment by smitpatel** [comment]
This is the query with Fetch/offset
```
SELECT [l].[Id], [l].[Level1_Optional_Id], [l].[Level1_Required_Id], [l].[Name], [l].[OneToMany_Optional_InverseId], [l].[OneToMany_Optional_Self_InverseId], [l].[OneToMany_Required_InverseId], [l].[OneToMany_Required_Self_InverseId], [l].[OneToOne_Optional_PK_InverseId], [l].[OneToOne_Optional_SelfId], [l0].[Id], [l0].[Level2_Optional_Id], [l0].[Level2_Required_Id], [l0].[Name], [l0].[OneToMany_Optional_InverseId], [l0].[OneToMany_Optional_Self_InverseId], [l0].[OneToMany_Required_InverseId], [l0].[OneToMany_Required_Self_InverseId], [l0].[OneToOne_Optional_PK_InverseId], [l0].[OneToOne_Optional_SelfId]
FROM [Level2] AS [l]
LEFT JOIN [Level3] AS [l0] ON [l0].[Level2_Optional_Id] = [l].[Id]
WHERE EXISTS (
    SELECT 1
    FROM [Level1] AS [e]
    LEFT JOIN (
        SELECT [e1].[Id], [e1].[Level1_Optional_Id], [e1].[Level1_Required_Id], [e1].[Name], [e1].[OneToMany_Optional_InverseId], [e1].[OneToMany_Optional_Self_InverseId], [e1].[OneToMany_Required_InverseId], [e1].[OneToMany_Required_Self_InverseId], [e1].[OneToOne_Optional_PK_InverseId], [e1].[OneToOne_Optional_SelfId]
        FROM [Level2] AS [e1]
    ) AS [t] ON [e].[Id] = [t].[Level1_Optional_Id]
    WHERE (([e].[Name] <> N'L1 03') OR [e].[Name] IS NULL) AND (([l].[OneToMany_Optional_InverseId] = [e].[Id]) AND [l].[OneToMany_Optional_InverseId] IS NOT NULL)
    ORDER BY @@ROWCOUNT
    OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY)
ORDER BY [l].[OneToMany_Optional_InverseId]
```
This is query with row number
```
SELECT [l].[Id], [l].[Level1_Optional_Id], [l].[Level1_Required_Id], [l].[Name], [l].[OneToMany_Optional_InverseId], [l].[OneToMany_Optional_Self_InverseId], [l].[OneToMany_Required_InverseId], [l].[OneToMany_Required_Self_InverseId], [l].[OneToOne_Optional_PK_InverseId], [l].[OneToOne_Optional_SelfId], [l0].[Id], [l0].[Level2_Optional_Id], [l0].[Level2_Required_Id], [l0].[Name], [l0].[OneToMany_Optional_InverseId], [l0].[OneToMany_Optional_Self_InverseId], [l0].[OneToMany_Required_InverseId], [l0].[OneToMany_Required_Self_InverseId], [l0].[OneToOne_Optional_PK_InverseId], [l0].[OneToOne_Optional_SelfId]
FROM [Level2] AS [l]
LEFT JOIN [Level3] AS [l0] ON [l0].[Level2_Optional_Id] = [l].[Id]
WHERE EXISTS (
    SELECT 1
    FROM (
        SELECT [e].[Id], [e].[Name], [e].[OneToMany_Optional_Self_InverseId], [e].[OneToMany_Required_Self_InverseId], [e].[OneToOne_Optional_SelfId], [t].[Id] AS [c0], [t].[Level1_Optional_Id], [t].[Level1_Required_Id], [t].[Name] AS [c1], [t].[OneToMany_Optional_InverseId], [t].[OneToMany_Optional_Self_InverseId] AS [c2], [t].[OneToMany_Required_InverseId], [t].[OneToMany_Required_Self_InverseId] AS [c3], [t].[OneToOne_Optional_PK_InverseId], [t].[OneToOne_Optional_SelfId] AS [c4], ROW_NUMBER() OVER(ORDER BY [e].[Id]) AS [__RowNumber__]
        FROM [Level1] AS [e]
        LEFT JOIN (
            SELECT [e1].[Id], [e1].[Level1_Optional_Id], [e1].[Level1_Required_Id], [e1].[Name], [e1].[OneToMany_Optional_InverseId], [e1].[OneToMany_Optional_Self_InverseId], [e1].[OneToMany_Required_InverseId], [e1].[OneToMany_Required_Self_InverseId], [e1].[OneToOne_Optional_PK_InverseId], [e1].[OneToOne_Optional_SelfId]
            FROM [Level2] AS [e1]
        ) AS [t] ON [e].[Id] = [t].[Level1_Optional_Id]
        WHERE ([e].[Name] <> N''L1 03'') OR [e].[Name] IS NULL
    ) AS [t0]
    WHERE (([t0].[__RowNumber__] > @__p_0) AND ([t0].[__RowNumber__] <= (@__p_0 + @__p_1))) AND ([l].[OneToMany_Optional_InverseId] = [t0].[Id]))
ORDER BY [l].[OneToMany_Optional_InverseId]
```
The difference in those queries is 
`(([l].[OneToMany_Optional_InverseId] = [e].[Id]) AND [l].[OneToMany_Optional_InverseId] IS NOT NULL)` &
`([l].[OneToMany_Optional_InverseId] = [t0].[Id]))`
 Looks like we are not applying null semantics on the predicate while using rownumber paging.

**Comment by maumar** [comment]
the  discrepancy @smitpatel noticed is due to overzealous null semantics application. It does not produce incorrect sql (just adds redundant null checks). Added https://github.com/aspnet/EntityFramework/issues/5670 to track this

**Comment by smitpatel** [comment]
:shipit:
