### PR TITLE
Set GenerateValueOnAdd flag for all Key properties by convention

### LINKED ISSUE #1116: Code First: Relational: Invalid database schema created when one-to-one association
The dependent table gets created with an Identity key, which doesn't work because it's an FK.

More generally, it is typically invalid to have a store generated FK. How should we handle? Check in model? Check in update pipeline? No explicit check?

### LINKED ISSUE #1126: SqlServer: Autogenerated integer values for composite PK
In present implementation SqlServer auto generates values for integer columns even if its a part of composite primary key which is not desirable by design.

### PR DESCRIPTION
**Pull request by smitpatel**
Implements #1271 
Added KeyConvention to set GenerateValueOnAdd flag(s) as true whenever new key is added.
If new key is existing foreign key then flag(s) are not set.
If foreign key is set on existing key then flag(s) are changed to false.
If foreign key is removed then the convention is run again on the key.

Resolves #1126 
In SqlServer provider,
for PK with only 1 property which is of common integer type, we assign SqlServerValueGenerationStrategy.Default annotation. Which is a pointer that this property can use Identity. If property level or model level value generation strategy is assigned then we use it otherwise Identity will be used as value generation strategy.
For all other cases, composite PK or PK with non-int property, we do nothing.

fixes #1116 
Due to above conventions, now the dependent end of FK doesn't have auto-generated value so there is no identity key in dependent table. ModelSnapshot still has Default as value generation strategy annotated which is valid model. And that whole area will change soon. Verified through sample project.

### CODE REVIEW

File: test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs [hunk 1]
```diff
@@ -20,7 +20,25 @@ protected override void OnModelCreating(ModelBuilder modelBuilder)
...
+                modelBuilder.Entity<Required1>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<Required2>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredAk1>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredAk2>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredNonPkSingle1>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredNonPkSingle2>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredNonPkSingleAk1>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredNonPkSingleAk2>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredSingleAk1>().Property(e => e.Id).ForSqlServer().UseSequence();
+                modelBuilder.Entity<RequiredSingleAk2>().Property(e => e.Id).ForSqlServer().UseSequence();
```
Comment (ajcvickers) [inline test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs]: It seems unfortunate that we have to do this now. Can we think about this some more and see if we can come up with a better experience?

File: test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs [hunk 2]
```diff
@@ -1801,20 +1801,25 @@ private static IModel BuildModel()
...
-            builder.Entity<Product>()
-                .HasOne(e => e.Tag).WithOne(e => e.Product)
-                .ReferencedKey<Product>(e => e.TagId)
-                .ForeignKey<ProductTag>(e => e.ProductId);
+            builder.Entity<Product>(b =>
+                {
+                    b.HasOne(e => e.Tag).WithOne(e => e.Product)
+                        .ReferencedKey<Product>(e => e.TagId)
+                        .ForeignKey<ProductTag>(e => e.ProductId);
+                    b.Property(e => e.TagId).GenerateValueOnAdd(false);
```
Comment (ajcvickers) [inline test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs]: What is it about TagId that means it should not have generate values on add set? And why is it that the conventions don't pick up on whatever this is and not set it?

Comment (ajcvickers) [inline test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs]: Likewise for other properties here where we are changing what the convention does.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+using System.Linq;
+using JetBrains.Annotations;
+using Microsoft.Data.Entity.Metadata;
+using Microsoft.Data.Entity.Metadata.Internal;
+using Microsoft.Data.Entity.Metadata.ModelConventions;
+using Microsoft.Data.Entity.Utilities;
+
+namespace Microsoft.Data.Entity.SqlServer.Metadata.ModelConventions
+{
+    public class SqlServerKeyConvention : IKeyConvention
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: I'm not sure that composite keys should get one property set as SQL Server Identity by default. Also, the fact that we have some essentially arbitrary rules that kick in to determine which property to use seems like not a great idea. It might be better to not set any property as Identity by convention and to let the app do this explicitly to one property if this is what the app needs.

Also, we want to switch over to make Sequences the default at some point, and we may be ready to do that now because Migrations support was holding us back, but that should now work. (We also may need a story for SQL Server versions that don't support sequences.) If using sequences becomes the default, then it's not clear when this would be useful. Also, multiple columns could use the sequence if needed, but I'm not sure we should do that by convention either.

We should discuss this with @divega.

**Comment by ajcvickers** [comment]
Ideally, no application should need to switch GenerateValueOnAdd off, so if we are having to do this in our test code, then we should understand why. The main reason for this is that even if GenerateValueOnAdd is on, then a value won't be generated if the user explicitly specifies a value before adding.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs (hunk 3 above)
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: I'm ok with not doing anything to composite keys for now.

File: test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs (hunk 2 above)
Comment (smitpatel) [inline test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs]: In the tests we are not assigning the values for TagId, Because of GenerateValueOnAdd being true the value generation assigns a value. This notifies PrincipalKeyChange. But the tests expect it to be null.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs (hunk 3 above)
Comment (divega) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: +1 It seems better to me not to try to be smart about value generation for composite key members.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+    {
+        private const string IdentityKeySuffix = "Id";
+        public virtual InternalKeyBuilder Apply(InternalKeyBuilder keyBuilder)
+        {
+            Check.NotNull(keyBuilder, nameof(keyBuilder));
+
+            var key = keyBuilder.Metadata;
+            var properties = key.Properties;
+
+            if (key == key.EntityType.TryGetPrimaryKey())
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: You can use key.IsPrimaryKey

File: test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs (hunk 1 above)
Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs]: I believe the last time we discussed this we decided that this case would be handled by 'lightweight conventions':

                foreach (var entityType in modelBuilder.Metadata.EntityTypes)
                {
                    var key = entityType.GetPrimaryKey();
                    if (key.Properties.Count == 1)
                    {
                        var keyProperty = key.Properties.Single();
                        modelBuilder.Entity(entityType.Name)
                            .Property(keyProperty.PropertyType, keyProperty.Name)
                            .ForSqlServer()
                            .UseSequence();
                    }
                }

**Comment by AndriySvyryd** [comment]
:shipit: pending signoff from Arthur

File: test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs (hunk 1 above)
Comment (ajcvickers) [inline test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs]: We have a convention that sets Identity on a primary key column if neither Identity or Sequence is explicitly set. (As noted in previous comments, this should be simplified so that it only sets Identity for single integer keys, not composites.) Can we not change this convention to set Identity or Sequence based on what is annotated at the model level?

File: test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs (hunk 2 above)
Comment (ajcvickers) [inline test/EntityFramework.Core.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs]: That makes sense given that this is a unit test for this specific behavior. Thanks.

File: test/EntityFramework.SqlServer.FunctionalTests/CompositeKeyEndToEndTest.cs [hunk 5]
```diff
@@ -201,22 +201,15 @@ protected override void OnConfiguring(DbContextOptions builder)
 
             protected override void OnModelCreating(ModelBuilder modelBuilder)
             {
-                modelBuilder.Entity<Pegasus>().Key(e => new { e.Id1, e.Id2 });
+                modelBuilder.Entity<Pegasus>(b =>
+                    {
+                        b.Key(e => new { e.Id1, e.Id2 });
+                        b.Property(e => e.Id1).GenerateValueOnAdd(false);
+                        b.Property(e => e.Id2).GenerateValueOnAdd(false);
```
Comment (ajcvickers) [inline test/EntityFramework.SqlServer.FunctionalTests/CompositeKeyEndToEndTest.cs]: Why do we need to switch GenerateValueOnAdd off here?

File: test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs [hunk 6]
```diff
@@ -217,43 +217,18 @@ protected override void OnModelCreating(ModelBuilder modelBuilder)
 
             modelBuilder.Entity<TBarcodeDetail>().Key(e => e.Code);
 
-            // TODO: Key should not get by-convention value generation if it is dependent of identifying relationship
-            modelBuilder.Entity<TResolution>()
-                .Property(e => e.ResolutionId)
-                .GenerateValueOnAdd(false);
```
Comment (ajcvickers) [inline test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs]: Why do we need to switch GenerateValueOnAdd off in all the cases here?

File: test/EntityFramework.Core.FunctionalTests/NullKeysTestBase.cs [hunk 7]
```diff
@@ -192,15 +192,24 @@ public virtual void OnModelCreating(ModelBuilder modelBuilder)
...
 
-                modelBuilder.Entity<WithNullableIntKey>()
-                    .HasMany(e => e.Dependents)
-                    .WithOne(e => e.Principal)
-                    .ForeignKey(e => e.Fk);
+                modelBuilder.Entity<WithNullableIntKey>(b =>
+                    {
+                        b.HasMany(e => e.Dependents)
+                            .WithOne(e => e.Principal)
+                            .ForeignKey(e => e.Fk);
```
Comment (ajcvickers) [inline test/EntityFramework.Core.FunctionalTests/NullKeysTestBase.cs]: Why do we need to switch GenerateValueOnAdd off in these cases?

File: test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs [hunk 8]
```diff
@@ -286,6 +261,8 @@ protected override void OnModelCreating(ModelBuilder modelBuilder)
             modelBuilder.Entity<TOrderLine>(b =>
                 {
                     b.Key(e => new { e.OrderId, e.ProductId });
+                    b.Property(e => e.OrderId).GenerateValueOnAdd(false);
```
Comment (ajcvickers) [inline test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs]: How about here?

File: test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs (hunk 1 above)
Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs]: The convention runs before the model is annotated.

Sent from my Windows Phone
________________________________

Comment (ajcvickers) [inline test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs]: Does that mean we need a convention that runs when the model is annotated so that changes to annotations can be responded to?

Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs]: We can do that, but it's much more granular than any conventions we have now or expect to have in near future.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs (hunk 3 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: After discussing with @AndriySvyryd  & @ajcvickers , 
we decided that we won't do anything for composite key. 
For PK with only 1 property and if that property is common integer type then we will add Default as value generation strategy.
Whenever SqlServerValueGenerationStrategy.Default is present, we use Identity only if there is no model level value generation strategy assigned.
In the absence of any input from what will be the value generation strategy, we use Identity.

File: test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs (hunk 6 above)
Comment (smitpatel) [inline test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs]: This was old code where we had to turn off the value generation for dependent end of relationship.
Removed now.

**Comment by smitpatel** [comment]
The previous KeyConvetion has been renamed to KeyDiscoveryConvention since it discovers the key properties. This new convention works on keys so it has been put in KeyConvention.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+
+        protected virtual void ConfigureDefaultValueGenerationOnProperty([NotNull] InternalPropertyBuilder propertyBuilder)
+        {
+            Check.NotNull(propertyBuilder, nameof(propertyBuilder));
+
+            propertyBuilder.Annotation(
+                SqlServerAnnotationNames.Prefix + SqlServerAnnotationNames.ValueGeneration,
+                SqlServerValueGenerationStrategy.Default.ToString(),
+                ConfigurationSource.Convention);
+        }
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: It's unfortunate that we don't use the sugar API here and instead restore to building annotation names and values manually. One of the advantages of the sugar API is that it creates a single place where the annotation name building happens. Can we investigate why the sugar API can't be used here? Maybe @AndriySvyryd knows?

File: src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs [hunk 10]
```diff
@@ -121,13 +121,21 @@ protected override IEnumerable<MigrationOperation> Add(IProperty target)
...
+                switch (property.SqlServer().ValueGenerationStrategy)
+                {
+                    case null:
+                        return property.EntityType.Model.SqlServer().ValueGenerationStrategy ?? default(SqlServerValueGenerationStrategy?);
+                    case SqlServerValueGenerationStrategy.Default:
+                        return property.EntityType.Model.SqlServer().ValueGenerationStrategy ?? SqlServerValueGenerationStrategy.Identity;
+                }
+                return property.SqlServer().ValueGenerationStrategy;
+            }
+            return default(SqlServerValueGenerationStrategy?);
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs]: This doesn't seem right to me. It seems like if a property has GenerateValueOnAdd, but doesn't have a ValueGenerationStrategy set, then it will use the generation strategy set on the model. I think it should only use the strategy set on the model if the property is annotated with Default.

Another way of thinking about this is that the SQL Server model building conventions are now entirely responsible for determining value generation strategy for each property. Migrations doesn't even need to look at GenerateValueOnAdd anymore. It just looks if the property is annotated. If it is, then it either sets that strategy directly, or if it is annotated as default it will instead use the strategy set on the model. If no strategy is set on the model it will use the overall default--currently Identity, soon to be Sequence. However, it might would be good to remove this last set and annotate the model in every case. Then if we change the default in the future existing models will continue to work without any additional work.

File: src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs [hunk 11]
```diff
@@ -38,8 +38,9 @@ public override ValueGenerator Select(IProperty property)
         {
             Check.NotNull(property, nameof(property));
 
-            var strategy = property.SqlServer().ValueGenerationStrategy
-                           ?? property.EntityType.Model.SqlServer().ValueGenerationStrategy;
+            var strategy = property.SqlServer().ValueGenerationStrategy == SqlServerValueGenerationStrategy.Default
+                ? (property.EntityType.Model.SqlServer().ValueGenerationStrategy ?? SqlServerValueGenerationStrategy.Identity)
+                : property.SqlServer().ValueGenerationStrategy ?? property.EntityType.Model.SqlServer().ValueGenerationStrategy;
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs]: If possible, factor the code here and the code used in Migrations into a common place, since in both places it is about finding the effective strategy for a given property.

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs (hunk 9 above)
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: There is no sugar API for internal model builders. We can add it if you think it will add value.

File: src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs (hunk 10 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs]: For composite PK, we don't set any annotation by conventions. What is expected behavior in such cases if user doesn't specify strategy. Presently all tests which have composite PK, uses Identity so it has been explicitly specified.

When a new key is added in SqlServer, GenerateValueOnAdd and annotation both are set. But if the key later becomes dependent end of FK then we set GenerateValue false but annotation still remains there. Therefore we are making check on GenerateValue.

Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs]: 1. The expected behavior is that if the property should use Identity, then that must be specified explicitly using the fluent API.

2. Annotation should be removed if it was added by convention.

File: src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs (hunk 11 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs]: Possible place to put method for refactoring?

Comment (ajcvickers) [inline src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs]: Same place ValueGenerationStrategy property is.

File: test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs [hunk 12]
```diff
@@ -45,37 +45,37 @@ public void Returns_built_in_generators_for_types_setup_for_value_generation()
...
 
-        [Fact]
-        public void Returns_sequence_value_generators_when_configured_for_model()
-        {
-            var model = BuildModel();
-            model.SqlServer().ValueGenerationStrategy = SqlServerValueGenerationStrategy.Sequence;
-            var entityType = model.GetEntityType(typeof(AnEntity));
+        //[Fact]
+        //public void Returns_sequence_value_generators_when_configured_for_model()
+        //{
```
Comment (smitpatel) [inline test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs]: @ajcvickers - This test fails because we use model annotation only if Default is applied to property.
Remove/modify?

File: src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs (hunk 11 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/SqlServerValueGeneratorSelector.cs]: Done.

File: src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs (hunk 10 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs]: Updated.
@AndriySvyryd - There are changed in conventions related to FK added and removed. Can you review again?

File: src/EntityFramework.SqlServer/Metadata/SqlServerValueGenerationStrategy.cs [hunk 13]
```diff
@@ -6,6 +6,7 @@ namespace Microsoft.Data.Entity.SqlServer.Metadata
     public enum SqlServerValueGenerationStrategy
     {
         Sequence,
-        Identity
+        Identity,
+        Default
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/SqlServerValueGenerationStrategy.cs]: Default should be first

File: src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs [hunk 14]
```diff
@@ -121,13 +121,14 @@ protected override IEnumerable<MigrationOperation> Add(IProperty target)
...
-            property.SqlServer().ValueGenerationStrategy
-            ?? property.EntityType.Model.SqlServer().ValueGenerationStrategy
-            ?? (property.GenerateValueOnAdd && property.PropertyType.IsInteger() && property.IsPrimaryKey()
-                ? SqlServerValueGenerationStrategy.Identity
-                : default(SqlServerValueGenerationStrategy?));
+        private SqlServerValueGenerationStrategy? GetValueGenerationStrategy(IProperty property)
+        {
+            if (property.GenerateValueOnAdd)
+            {
+                return SqlServerModelExtensions.GetSqlServerValueGenerationStrategy(property);
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs]: Since the convention will remove the annotation you don't need to check GenerateValueOnAdd here

File: test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs (hunk 12 above)
Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs]: Modify by applying Default to all properties. Also add another test that asserts that model annotation is not returned if property annotation is not set.

**Comment by AndriySvyryd** [comment]
Add a SqlServer-specific ModelBuilder test that asserts that the convention removes the strategy annotations on preprties that are included in a foreign key.

File: src/EntityFramework.Core/Metadata/ModelConventions/KeyConvention.cs [hunk 15]
```diff
@@ -1,82 +1,55 @@
...
-            var entityType = entityBuilder.Metadata;
+            Check.NotNull(keyBuilder, nameof(keyBuilder));
+
+            var entityBuilder = keyBuilder.ModelBuilder.Entity(keyBuilder.Metadata.EntityType.Name, ConfigurationSource.Convention);
+            var properties = keyBuilder.Metadata.Properties;
 
-            var keyProperties = DiscoverKeyProperties(entityType);
-            if (keyProperties.Count != 0
-                && entityBuilder.PrimaryKey(keyProperties.Select(p => p.Name).ToList(), ConfigurationSource.Convention) != null)
+            if (entityBuilder.Metadata.TryGetForeignKey(properties) == null)
```
Comment (AndriySvyryd) [inline src/EntityFramework.Core/Metadata/ModelConventions/KeyConvention.cs]: This condition will return true for a composite key where a foreign key is defined on only a subset of properties or a key whose properties are a subset of foreign key properties. Change the check to account for this and add tests.

File: src/EntityFramework.Core/Metadata/ModelConventions/KeyConvention.cs [hunk 16]
```diff
@@ -1,82 +1,55 @@
...
+            Check.NotNull(entityBuilder, nameof(entityBuilder));
+            Check.NotNull(foreignKey, nameof(foreignKey));
+
+            var properties = foreignKey.Properties;
 
-            return type == typeof(int)
-                   || type == typeof(long)
-                   || type == typeof(short)
-                   || type == typeof(byte);
+            if (entityBuilder.Metadata.TryGetForeignKey(properties) == null)
```
Comment (AndriySvyryd) [inline src/EntityFramework.Core/Metadata/ModelConventions/KeyConvention.cs]: Same as above. Extract check to a method to avoid duplicate logic.

File: src/EntityFramework.Core/Metadata/ModelConventions/KeyDiscoveryConvention.cs [hunk 17]
```diff
@@ -0,0 +1,57 @@
...
+            {
+                keyProperties = entityType.Properties.Where(
+                    p => string.Equals(p.Name, entityType.SimpleName + KeySuffix, StringComparison.OrdinalIgnoreCase))
+                    .ToList();
+            }
+
+            if (keyProperties.Count > 1)
+            {
+                //TODO - add in logging using resource Strings.MultiplePropertiesMatchedAsKeys()
+                return Enumerable.Empty<Property>().ToList();
```
Comment (AndriySvyryd) [inline src/EntityFramework.Core/Metadata/ModelConventions/KeyDiscoveryConvention.cs]: This isn't related to your changes, but change this line to return new Property[0]

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerForeignKeyAddedConvention.cs [hunk 18]
```diff
@@ -0,0 +1,37 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using JetBrains.Annotations;
+using Microsoft.Data.Entity.Metadata.Internal;
+using Microsoft.Data.Entity.Metadata.ModelConventions;
+using Microsoft.Data.Entity.Utilities;
+
+namespace Microsoft.Data.Entity.SqlServer.Metadata.ModelConventions
+{
+    public class SqlServerForeignKeyAddedConvention : IRelationshipConvention
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerForeignKeyAddedConvention.cs]: Merge with SqlServerKeyConvention and rename to SqlServerValueGenerationStrategyConvention

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerForeignKeyAddedConvention.cs [hunk 19]
```diff
@@ -0,0 +1,37 @@
...
+                if (property.GenerateValueOnAdd == false)
+                {
+                    var entityBuilder = relationshipBuilder.ModelBuilder.Entity(property.EntityType.Name, ConfigurationSource.Convention);
+                    RemoveValueGenerationStrategyAnnotaion(entityBuilder.Property(property.PropertyType, property.Name, ConfigurationSource.Convention));
+                }
+            }
+            return relationshipBuilder;
+        }
+
+        protected virtual void RemoveValueGenerationStrategyAnnotaion([NotNull] InternalPropertyBuilder propertyBuilder)
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerForeignKeyAddedConvention.cs]: typo in 'Annotaion'

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+{
+    public class SqlServerKeyConvention : IKeyConvention, IForeignKeyRemovedConvention
+    {
+        public virtual InternalKeyBuilder Apply(InternalKeyBuilder keyBuilder)
+        {
+            Check.NotNull(keyBuilder, nameof(keyBuilder));
+
+            var key = keyBuilder.Metadata;
+
+            if (key.IsPrimaryKey() && key.Properties.Count == 1 && key.Properties.First().PropertyType.IsInteger())
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: Also need to check that ValueGeneratedOnAdd is true

File: src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs [hunk 21]
```diff
@@ -0,0 +1,58 @@
...
+            Check.NotNull(entityBuilder, nameof(entityBuilder));
+            Check.NotNull(foreignKey, nameof(foreignKey));
+
+            var properties = foreignKey.Properties;
+
+            if (entityBuilder.Metadata.TryGetForeignKey(properties) == null
+                && entityBuilder.Metadata.TryGetPrimaryKey(properties) != null
+                && properties.Count == 1
+                && properties.First().PropertyType.IsInteger())
+            {
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerKeyConvention.cs]: No need to check for existing foreign keys, just that ValueGeneratedOnAdd is true. Extract logic to avoid duplication.

File: src/EntityFramework.SqlServer/Metadata/SqlServerModelExtensions.cs [hunk 22]
```diff
@@ -72,5 +72,14 @@ public virtual Sequence GetOrAddSequence([CanBeNull] string name = null, [CanBeN
             return ((Model)Model).SqlServer().TryGetSequence(name, schema)
                    ?? AddOrReplaceSequence(new Sequence(name, schema));
         }
+
+        internal static SqlServerValueGenerationStrategy? GetSqlServerValueGenerationStrategy([NotNull] IProperty property)
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/SqlServerModelExtensions.cs]: This should be public.

Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/SqlServerModelExtensions.cs]: And should be defined on ReadOnlySqlServerModelExtensions because it is only about inspecting metadata, not changing it.

File: src/EntityFramework.SqlServer/Metadata/SqlServerModelExtensions.cs [hunk 23]
```diff
@@ -72,5 +72,14 @@ public virtual Sequence GetOrAddSequence([CanBeNull] string name = null, [CanBeN
...
+        {
+            Check.NotNull(property, nameof(property));
+
+            return property.SqlServer().ValueGenerationStrategy == SqlServerValueGenerationStrategy.Default
+                ? (property.EntityType.Model.SqlServer().ValueGenerationStrategy ?? SqlServerValueGenerationStrategy.Identity)
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/SqlServerModelExtensions.cs]: Can you make the change to always put the default value generation strategy in the model rather than hard code it here? Or file another issue to do so if you prefer.

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs [hunk 24]
```diff
@@ -76,7 +76,7 @@ public virtual Sequence TryGetSequence()
             var modelExtensions = Property.EntityType.Model.SqlServer();
 
             if (ValueGenerationStrategy != SqlServerValueGenerationStrategy.Sequence
-                && (ValueGenerationStrategy != null
+                && ((ValueGenerationStrategy != null && ValueGenerationStrategy != SqlServerValueGenerationStrategy.Default)
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs]: Can you use GetSqlServerValueGenerationStrategy here?

Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs]: This would fix the logic as currently it will return the model strategy if property strategy is null

File: test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs (hunk 12 above)
Comment (ajcvickers) [inline test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs]: Consider using the SQL Server conventions with the model builder. This will then test that given the SQL Server conventions and the model annotated with Sequence, the correct generators are used for the correct properties.

File: src/EntityFramework.SqlServer/SqlServerModelBuilderFactory.cs [hunk 25]
```diff
@@ -2,10 +2,24 @@
...
     {
+        protected override ConventionSet CreateConventionSet()
+        {
+            var conventions = base.CreateConventionSet();
+
+            conventions.KeyAddedConventions.Add(new SqlServerKeyConvention());
+
+            conventions.ForeignKeyAddedConventions.Add(new SqlServerForeignKeyAddedConvention());
+
+            conventions.ForeignKeyRemovedConventions.Add(new SqlServerKeyConvention());
```
Comment (AndriySvyryd) [inline src/EntityFramework.SqlServer/SqlServerModelBuilderFactory.cs]: Memory: add the same instance

File: test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs (hunk 12 above)
Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs]: @ajcvickers I think that would be a different, functional test that I mentioned in a previous comment. These unit tests shouldn't depend on correctness of the conventions.

Comment (ajcvickers) [inline test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs]: @AndriySvyryd I'm fine with that so long as the functional test is added.

File: test/EntityFramework.SqlServer.FunctionalTests/BatchingTest.cs [hunk 26]
```diff
@@ -46,7 +47,8 @@ public BloggingContext(IServiceProvider serviceProvider, DbContextOptions option
 
             protected override void OnModelCreating(ModelBuilder modelBuilder)
             {
-                modelBuilder.Entity<Blog>().Property(b => b.Id).GenerateValueOnAdd(generateValue: false);
+                modelBuilder.Entity<Blog>().Property(b => b.Id).GenerateValueOnAdd(generateValue: false)
+                    .Metadata.RemoveAnnotation(new Annotation(SqlServerAnnotationNames.Prefix + SqlServerAnnotationNames.ValueGeneration, "_"));
```
Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.FunctionalTests/BatchingTest.cs]: We should add sugar API for removing this annotation

File: test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs [hunk 27]
```diff
@@ -105,6 +107,7 @@ public void Block_size_is_obtained_from_named_model_default_sequence()
                 .Entity<Robot>()
                 .Property(e => e.Id)
                 .GenerateValueOnAdd()
+                .Annotation(SqlServerAnnotationNames.Prefix + SqlServerAnnotationNames.ValueGeneration, SqlServerValueGenerationStrategy.Default.ToString())
```
Comment (AndriySvyryd) [inline test/EntityFramework.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs]: You should be able to use the sugar API in these cases.

**Comment by AndriySvyryd** [comment]
:shipit:

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs [hunk 28]
```diff
@@ -68,5 +68,14 @@ public override Sequence TryGetSequence(string name, string schema = null)
             return FindSequence(SqlServerSequenceAnnotation + schema + "." + name)
                    ?? base.TryGetSequence(name, schema);
         }
+
+        public static SqlServerValueGenerationStrategy? GetSqlServerValueGenerationStrategy([NotNull] IProperty property)
+        {
+            Check.NotNull(property, nameof(property));
+
+            return property.SqlServer().ValueGenerationStrategy == SqlServerValueGenerationStrategy.Default
+                ? (property.EntityType.Model.SqlServer().ValueGenerationStrategy ?? SqlServerValueGenerationStrategy.Identity)
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs]: Did you file an issue to not return Identity by default but instead always put it in the model?

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs [hunk 29]
```diff
@@ -76,7 +76,7 @@ public virtual Sequence TryGetSequence()
             var modelExtensions = Property.EntityType.Model.SqlServer();
 
             if (ValueGenerationStrategy != SqlServerValueGenerationStrategy.Sequence
-                && (ValueGenerationStrategy != null
+                && (ValueGenerationStrategy != SqlServerValueGenerationStrategy.Default
                     || modelExtensions.ValueGenerationStrategy != SqlServerValueGenerationStrategy.Sequence))
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs]: Can you use GetSqlServerValueGenerationStrategy here?

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs [hunk 30]
```diff
@@ -68,5 +68,14 @@ public override Sequence TryGetSequence(string name, string schema = null)
             return FindSequence(SqlServerSequenceAnnotation + schema + "." + name)
                    ?? base.TryGetSequence(name, schema);
         }
+
+        public static SqlServerValueGenerationStrategy? GetSqlServerValueGenerationStrategy([NotNull] IProperty property)
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs]: Why is this a static method here instead of an instance method on the property extensions?

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs (hunk 28 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs]: filed #1811

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs (hunk 30 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs]: moved to property extension ValueGenerationStrategy property

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs (hunk 29 above)
Comment (smitpatel) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs]: Simplified.

**Comment by smitpatel** [comment]
Updated with feedback.

File: src/EntityFramework.SqlServer/Metadata/SqlServerPropertyBuilder.cs [hunk 31]
```diff
@@ -92,5 +92,23 @@ public virtual SqlServerPropertyBuilder UseIdentity()
 
             return this;
         }
+
+        public virtual SqlServerPropertyBuilder UseDefault()
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/SqlServerPropertyBuilder.cs]: Can't call this UseDefault because there is no indication as to what "default" this is. Change to UseDefaultValueGeneration for now, but we should review these names in API review and also review whether to change to just one method with a parameter.

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs [hunk 32]
```diff
@@ -57,7 +57,10 @@ public override object DefaultValue
             {
                 // TODO: Issue #777: Non-string annotations
                 var value = Property[SqlServerValueGenerationAnnotation];
-                return value == null ? null : (SqlServerValueGenerationStrategy?)Enum.Parse(typeof(SqlServerValueGenerationStrategy), value);
+                var strategy = value == null ? null : (SqlServerValueGenerationStrategy?)Enum.Parse(typeof(SqlServerValueGenerationStrategy), value);
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs]: Consider using null propagation operator.

File: src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs [hunk 33]
```diff
@@ -68,5 +68,5 @@ public override Sequence TryGetSequence(string name, string schema = null)
             return FindSequence(SqlServerSequenceAnnotation + schema + "." + name)
                    ?? base.TryGetSequence(name, schema);
         }
-    }
+        }
```
Comment (ajcvickers) [inline src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerModelExtensions.cs]: Fix whitespace

**Comment by ajcvickers** [comment]
:shipit:
