### PR TITLE
Fix to #5454 - Error when using Where with reference

### LINKED ISSUE #5454: Error when using Where with reference
I'm trying to figure out why the following command doesn't work:

``` csharp
var availability = await context.UserAvailabilities
    .Where(t => t.User.Id == user.Id && t.User.IsProfessional)
    .ToListAsync();
```

I'm getting this error (Sorry about the size...):

```An unhandled exception has occurred while executing the request
System.ArgumentException: Expression of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[UPlatform.Models.UserAvailability,System.Collections.Generic.IAsyncEnumerable`1[UPlatform.Models.ApplicationUser]],UPlatform.Models.ApplicationUser],System.Nullable`1[System.Boolean]]' cannot be used for parameter of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[UPlatform.Models.UserAvailability,System.Collections.Generic.IAsyncEnumerable`1[UPlatform.Models.ApplicationUser]],UPlatform.Models.ApplicationUser],System.Boolean]' of method 'System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[UPlatform.Models.UserAvailability,System.Collections.Generic.IAsyncEnumerable`1[UPlatform.Models.ApplicationUser]],UPlatform.Models.ApplicationUser]] _Where[TransparentIdentifier`2](System.Collections.Generic.IAsyncEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[UPlatform.Models.UserAvailability,System.Collections.Generic.IAsyncEnumerable`1[UPlatform.Models.ApplicationUser]],UPlatform.Models.ApplicationUser]], System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[UPlatform.Models.UserAvailability,System.Collections.Generic.IAsyncEnumerable`1[UPlatform.Models.ApplicationUser]],UPlatform.Models.ApplicationUser],System.Boolean])'```

I thought it was because the table is empty and there is some problem when I'm trying to use the **t.User** property, but isn't. Wherever I try to access the **User** property reference, I get this error. 

This strange behaviour starts when I updated to **1.0.0-rc2** versions.

If I remove the `Where` clausure, it works:

```csharp
var availability = await context.UserAvailabilities.ToListAsync();
```

I already tried to replace `ToListAsync()` by `ToList()`, but I'm getting the same error.

Any help will be welcome. 👍

Thanks

### PR DESCRIPTION
**Pull request by maumar**
Fixes #5454 

Problem was for happening for queries with optional navigations like so:

context.Orders.Where(o => o.Customer.IsVip)

In this case Customer can be nullable, so IsVip can also be nullable. We compensate for this by introducing the following:

context.Orders.Where(o => o.Customer != null ? (bool?)o.Customer.IsVip : (bool?)null)

However, we didn't convert it back to the original type (users had to introduce those casts themselves). Without the cast, those queries were throwing compile-time exceptions that were not very informative.

Fix is to cast back to the original type requested by user:

context.Orders.Where(o => (bool)(o.Customer != null ? (bool?)o.Customer.IsVip : (bool?)null))

This still may cause runtime errors if o.Customer is actually null, but those are much more understandable now.

Also fixed compilation errors for complex Skip/Take arguments. Those are evaluated on the client for the time being.

### CODE REVIEW

**Comment by maumar** [comment]
@anpete @smitpatel

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs [hunk 1]
```diff
@@ -650,9 +650,22 @@ private static Expression HandleSkip(HandlerContext handlerContext)
         {
             var skipResultOperator = (SkipResultOperator)handlerContext.ResultOperator;
 
-            handlerContext.SelectExpression.Offset = skipResultOperator.Count;
+            var sqlTranslatingExpressionVisitor
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs]: Can you make this visitor creation into a method on HandlerContext. I.e. handlerContext.CreateSqlTranslatingVisitor

**Comment by anpete** [comment]
:shipit:

**Comment by anpete** [comment]
Is there a test for the Skip/Take change?

**Comment by anpete** [comment]
Reminder to also do a R# pass.

**Comment by maumar** [comment]
tests are: 'Optional_navigation_type_compensation_works_with_skip' and 'Optional_navigation_type_compensation_works_with_take'
