### PR TITLE
Properly track dependent entities when queried.

### LINKED ISSUE #9086: Cascade delete throws for owned entities
From @arjenvrh https://github.com/aspnet/EntityFramework/issues/8923#issuecomment-313422001:
I tried out the Owner Types in Preview2 with the following classes:
```C#
public class ParentClass {
    [Required]
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid Id { get; set; }
    
    public virtual OwnedClass Ref { get; set; }
}

public class OwnedClass
{
    public string Field1 { get; set; }
    public string Field2 { get; set; }
}
```
and the following Mapping:
```
modelBuilder.Entity<ParentClass>()
    .OwnsOne<OwnedClass>(s => s.Ref, cb =>
    {
        cb.Property(c => c.Field1).HasColumnName("OwnedField1");
        cb.Property(c => c.Field2).HasColumnName("OwnedField2");
    });
```

When I try to delete a ParentClass item it throws an error of the ChangeTracker with a KeyNotFoundException.

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fix shadow owned types.

Fixes #9086

### CODE REVIEW

File: src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs [hunk 1]
```diff
@@ -960,7 +960,8 @@ private bool CanSetUnique(bool unique, ConfigurationSource? configurationSource,
                 return false;
             }
 
-            if ((Metadata.PrincipalToDependent != null)
+            if (Metadata.PrincipalToDependent != null
+                && !Metadata.PrincipalToDependent.IsShadowProperty
```
Comment (ajcvickers) [inline src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs]: Shadow nav property?

Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs]: yes, for snapshot

File: src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs [hunk 2]
```diff
@@ -1735,6 +1735,7 @@ private static IndexBuilderSnapshot DetachIndex(Index indexToDetach)
                 if (builder != null)
                 {
                     builder = builder.RelatedEntityTypes(Metadata, existingNavigation.GetTargetType(), configurationSource);
+                    builder = builder?.IsRequired(true, configurationSource);
```
Comment (ajcvickers) [inline src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: Does this means Owns always means required?

Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: Yes, it has to be, since it creates an identifying fk.

File: src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs (hunk 1 above)
Comment (ajcvickers) [inline src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs]: Doh. 🤦‍♂️

File: src/EFCore/ChangeTracking/Internal/StateManager.cs [hunk 3]
```diff
@@ -166,28 +166,35 @@ public virtual InternalEntityEntry GetOrCreateEntry(object entity, IEntityType e
...
+        }
 
-                    entries[entity] = entry;
+        private void AddToReferenceMap(InternalEntityEntry entry)
+        {
+            var mapKey = entry.Entity ?? entry;
+            var entityType = entry.EntityType;
+            if (entityType.HasDefiningNavigation())
+            {
+                foreach (var otherDiet in _model.GetEntityTypes(entityType.Name)
```
Comment (smitpatel) [inline src/EFCore/ChangeTracking/Internal/StateManager.cs]: can you remove "diet"
