### PR TITLE
SQL Server Migrations: Only SET IDENTITY_INSERT when IDENTITY

### LINKED ISSUE #8618: Migrations: InsertData() causes error "Table 'table_name' does not have the identity property. Cannot perform SET operation."
Our implementation for SQL Server is incorrect because `SET IDENTITY_INSERT table_name ON` is only valid when the table does actually have an identity column. I see a few options:

1. Have a flag indicating if the statement should be generated
2. Have a separate method e.g. `InsertDataOverridingIdentity` :smile_cat:
3. Query for schema metadata in the SQL (might not work if we don't have enough permissions).

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #8618

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -828,21 +828,55 @@ protected override void Generate([NotNull] SqlOperation operation, [CanBeNull] I
             Check.NotNull(operation, nameof(operation));
             Check.NotNull(builder, nameof(builder));
 
+            builder.Append("IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [object_id] = OBJECT_ID(N'");
```
Comment (ajcvickers) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs]: Do we know we will have permission for this query?

Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs]: No idea, but we query sys tables in other places too.

Comment (ajcvickers) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs]: Thought about it more and I think it's fine for code in Migrations that is already doing schema stuff.
