### PR TITLE
Fix #4975 - EF.Property<T> property name shoud not be parameterized

### LINKED ISSUE #4975: Query caches property name on EF.Property<T> closure
When a query on a shadow property takes the property name as a parameter, the parameter name is cached on the first call and not respected in successive calls.

The following test fails on the second Assert:
```cs
        [ConditionalFact]
        public virtual void Where_shadow_closure()
        {
            var propertyName = "Title";
            var value = "Sales Representative";

            AssertQuery<Employee>(
                es => es.Where(e => EF.Property<string>(e, propertyName) == value),
                entryCount: 6);

            propertyName = "FirstName";
            value = "Steven";

            AssertQuery<Employee>(
                es => es.Where(e => EF.Property<string>(e, propertyName) == value),
                entryCount: 1);
        }
```

Generated SQL (Second query still referencing `Title` and not `FirstName`):
```sql
@__value_0: Sales Representative

SELECT [e].[EmployeeID], [e].[City], [e].[Country], [e].[FirstName], [e].[ReportsTo], [e].[Title]
FROM [Employees] AS [e]
WHERE [e].[Title] = @__value_0

@__value_0: Steven

SELECT [e].[EmployeeID], [e].[City], [e].[Country], [e].[FirstName], [e].[ReportsTo], [e].[Title]
FROM [Employees] AS [e]
WHERE [e].[Title] = @__value_0
```

### PR DESCRIPTION
**Pull request by mikary**
Implementing the solution proposed in #4975. Also includes minor change to `ParameterExtractingExpressionVisitor` because the attribute was not being checked due to a performance optimization.
@anpete @maumar

### CODE REVIEW

File: test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs [hunk 1]
```diff
@@ -4689,6 +4689,24 @@ public virtual void Where_Property_when_shadow()
         }
 
         [ConditionalFact]
+        public virtual void Where_Property_shadow_closure()
```
Comment (maumar) [inline test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs]: we could add tests where we reference static field and/or property

**Comment by maumar** [comment]
:shipit:

File: test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs (hunk 1 above)
Comment (mikary) [inline test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs]: Looks like we already have a few tests to cover these kinds of cases (i.e. `Where_static_field_access_closure_via_query_cache`)
