### PR TITLE
Query: Convert SetOperator.Source2 from EntityQueryable to QueryModel…

### LINKED ISSUE #7279: Set Operations throw ArgumentNullException when second source is dbset
Simple LINQ query with `Concat` throws `ArgumentNullException`

```
Exception message:
System.ArgumentNullException
Value cannot be null.
Parameter name: querySource

Stack trace:
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName) in D:\EntityFramework\src\Shared\Check.cs:line 27
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.AddQuery(IQuerySource querySource, SelectExpression selectExpression) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs:line 258
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\ExpressionVisitors\RelationalEntityQueryableExpressionVisitor.cs:line 159
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\EntityQueryableExpressionVisitor.cs:line 35
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ExpressionVisitors\ExpressionVisitorBase.cs:line 26
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 1218
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleSetOperation(EntityQueryModelVisitor entityQueryModelVisitor, Expression secondSource, MethodInfo setMethodInfo) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 328
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleConcat(EntityQueryModelVisitor entityQueryModelVisitor, ConcatResultOperator concatResultOperator) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 133
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.<>c.<.cctor>b__30_4(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel __) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 33
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 78
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs:line 71
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs:line 168
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 1077
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs:line 1187
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 721
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs:line 373
   at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.SqlServer\Query\Internal\SqlServerQueryModelVisitor.cs:line 92
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 259
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Storage\Database.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 218
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0() in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 171
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\CompiledQueryCache.cs:line 68
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\CompiledQueryCache.cs:line 45
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 169
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 99
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\EntityQueryProvider.cs:line 57
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.Concat_simple() in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Specification.Tests\QueryTestBase.cs:line 5941
```

### Steps to reproduce
Remove Where conditions from the existing test `Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase<TFixture>.Concat_simple` and run it against SqlServer or InMemory database
```c#
        [ConditionalFact]
        public virtual void Concat_simple()
        {
            using (var context = CreateContext())
            {
                var query1 = context.Set<Customer>()
                    ;//.Where(c => c.City == "México D.F.");

                var query2 = context.Set<Customer>()
                    ;//.Where(s => s.ContactTitle == "Owner");

                var query3 = query1.Concat(query2).ToList(); // <<< ArgumentNullException

                Assert.Equal(182, query3.Count);
            }
        }
```

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 7 Professional SP1
IDE: Visual Studio 2015

### PR DESCRIPTION
**Pull request by smitpatel**
… when applicable.

This causes issue when translating EntityQueryable to SelectExpression as there is no query source.

resolves #7279

### CODE REVIEW

File: src/EFCore/Query/Internal/QueryOptimizer.cs [hunk 1]
```diff
@@ -141,11 +140,7 @@ var additionalFromClause
                 = queryModel.BodyClauses.ElementAtOrDefault(index + 1)
                     as AdditionalFromClause;
 
-            var querySourceReferenceExpression
-                = additionalFromClause?.FromExpression as QuerySourceReferenceExpression;
-
-            if (querySourceReferenceExpression != null
-                && querySourceReferenceExpression.ReferencedQuerySource == groupJoinClause)
+            if (additionalFromClause?.FromExpression is QuerySourceReferenceExpression querySourceReferenceExpression && querySourceReferenceExpression.ReferencedQuerySource == groupJoinClause)
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: nit: formatting (add newline before &&

File: src/EFCore/Query/Internal/QueryOptimizer.cs [hunk 2]
```diff
@@ -309,5 +301,48 @@ var newMainFromClause
...
+        {
+            switch (resultOperator)
+            {
+                case ExceptResultOperator exceptResultOperator
+                when IsEntityQueryable(exceptResultOperator.Source2):
+                    exceptResultOperator.Source2 = ConvertEntityQueryableToSubQuery(exceptResultOperator.Source2);
+                    break;
+
+                case ConcatResultOperator concatResultOperator
+                    when IsEntityQueryable(concatResultOperator.Source2):
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: nit: make indentations consistent

File: src/EFCore/Query/Internal/QueryOptimizer.cs [hunk 3]
```diff
@@ -309,5 +301,48 @@ var newMainFromClause
...
+
+        private static bool IsEntityQueryable(Expression expression)
+        {
+            return expression is ConstantExpression constantExpression
+                   && constantExpression.Type.GetGenericTypeDefinition() == typeof(EntityQueryable<>);
+        }
+
+        private static SubQueryExpression ConvertEntityQueryableToSubQuery(Expression expression)
+        {
+            var mainFromClause = new MainFromClause("set_" + _setOperatorCount++, expression.Type.GenericTypeArguments[0], expression);
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: add some funky characters to the name that would prevent clashes, just like relinq does for their generated item names (e.g. ```"<set_1>"```)

**Comment by smitpatel** [comment]
Updated.

File: src/EFCore/Query/Internal/QueryOptimizer.cs [hunk 4]
```diff
@@ -309,5 +303,51 @@ var newMainFromClause
...
+                case UnionResultOperator unionResultOperator
+                when IsEntityQueryable(unionResultOperator.Source2):
+                    unionResultOperator.Source2 = ConvertEntityQueryableToSubQuery(unionResultOperator.Source2);
+                    break;
+            }
+        }
+
+        private static bool IsEntityQueryable(Expression expression)
+        {
+            return expression is ConstantExpression constantExpression
```
Comment (maumar) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: is constantExpression guaranteed to be of generic type? Otherwise this line will throw. Maybe add defensive check.

Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: Done. Added check to verify if the type is generic.

Comment (anpete) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: DRY this with other 3 places in stack.

File: src/EFCore/Query/Internal/QueryOptimizer.cs [hunk 5]
```diff
@@ -309,5 +303,52 @@ var newMainFromClause
...
+                   && constantExpression.Type.IsConstructedGenericType
+                   && constantExpression.Type.GetGenericTypeDefinition() == typeof(EntityQueryable<>);
+        }
+
+        private static SubQueryExpression ConvertEntityQueryableToSubQuery(Expression expression)
+        {
+            var mainFromClause = new MainFromClause(
+                $"<set>_{_setOperatorCount++}",
```
Comment (anpete) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: Use a better name? Type name

File: src/EFCore/Query/Internal/QueryOptimizer.cs (hunk 4 above)
Comment (smitpatel) [inline src/EFCore/Query/Internal/QueryOptimizer.cs]: For reference #8074
