### PR TITLE
Query: Allow translations through DTO objects

### LINKED ISSUE #7234: Query: Translate Distinct to SQL when applied after custom projection
I looked up for this problem and didn't find anything. Sorry if I'm making a dup or I messed up something.

This
```c#
context.Blogs
    .Select(t => new BlogDto
    {
        Url = t.Url
    })
    .Distinct()
    .ToList();
```
resulted in the following query:
```sql
SELECT [t].[Url]
FROM [Blogs] AS [t]
```
and I expected:
```sql
SELECT DISTINCT [t].[Url]
FROM [Blogs] AS [t]   
```

So, now I'm using the following workaround:

```c#
context.Blogs
    .Select(t => new
    {
        Url = t.Url
    })
    .Distinct()
    .Select(t => new BlogDto
    {
        Url = t.Url
    })
    .ToList();
```

which results in:

```sql
SELECT [t1].[Url]
FROM (
    SELECT DISTINCT [t0].[Url]
    FROM [Blogs] AS [t0]
) AS [t1]
```

### Steps to reproduce

```c#
    public class BlogDto
    {
        public string Url { get; set; }
    }

    public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Data Source=.;Initial Catalog=Blogging;Integrated Security=True;MultipleActiveResultSets=True");
            //optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=CollectionsTest;Trusted_Connection=True;ConnectRetryCount=0");
        }
    }

    public class Program
    {
        private static void Main()
        {
            using (var context = new BlogContext())
            {
                var results = context.Blogs
                    .Select(t => new BlogDto
                    {
                        Url = t.Url
                    })
                    .Distinct()
                    .ToList();
            }
        }
    }
```

Just to be clear, the following works as expected:
```c#
context.Blogs
    .Select(t => new
    {
        Url = t.Url
    })
    .Distinct()
    .ToList();
``` 
produces:

```sql
SELECT DISTINCT [t].[Url]
FROM [Blogs] AS [t]
```

I have one simple question regarding terminology. When you say 'projection' ('projecting' to some object different from the model), does that include anonymous objects? If so, the title of this issue should be "Projecting to a specific object(class) with Distinct is not working as expected"

Thank you!

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 8.1 64bit
IDE: Visual Studio 2015 Update 3

### PR DESCRIPTION
**Pull request by smitpatel**
DTO which are projected out, (from any level) are materialized correctly with typed projection shaper
Store member bindings for MemberInitExpression to allow binding after DTO projection

Resolves #7234

### CODE REVIEW

File: src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs [hunk 1]
```diff
@@ -53,6 +52,45 @@ private new RelationalQueryModelVisitor QueryModelVisitor
...
+        /// <returns>
+        ///     An Expression corresponding to the translated member init.
+        /// </returns>
+        protected override Expression VisitMemberInit(MemberInitExpression memberInitExpression)
+        {
+            var newMemberInitExpression = base.VisitMemberInit(memberInitExpression);
+
+            var selectExpression = QueryModelVisitor.TryGetQuery(_querySource);
+
+            if (selectExpression != null)
```
Comment (anpete) [inline src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs]: DRY this with VisitNew

File: src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs [hunk 2]
```diff
@@ -53,6 +52,45 @@ private new RelationalQueryModelVisitor QueryModelVisitor
...
+            {
+                foreach (var sourceBinding in memberInitExpression.Bindings)
+                {
+                    if (sourceBinding is MemberAssignment memberAssignment)
+                    {
+                        var sourceExpression = memberAssignment.Expression;
+
+                        if (_sourceExpressionProjectionMapping.ContainsKey(sourceExpression))
```
Comment (anpete) [inline src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs]: Why not TryGetValue?

File: src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs (hunk 1 above)
Comment (smitpatel) [inline src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs]: based on the complex logic of finding member id in NewExpression (since newExpression.Members can be null), it provides no value to DRY it.

**Comment by smitpatel** [comment]
Updated.
