### PR TITLE
Query: Use short-circuiting in predicates based on parameter values

### LINKED ISSUE #5736: Query: Short-circuiting is not working
### Steps to reproduce

``` C#
        public async Task<List<ContentItem>> GetContentItems(int siteID, int menuID, int? groupID, DateTime? dateFilter)
        {
            var query = from item in db.ContentItems
                        from mi in item.MenuContentItems
                        where (menuID == 0 || mi.MenuID == menuID) 
                        && (groupID == null || groupID == 0 || item.ContentGroupID == groupID)
                        && ((dateFilter == null) || (item.PublishDate.HasValue && item.PublishDate.Value.Month == dateFilter.Value.Month && item.PublishDate.Value.Year == dateFilter.Value.Year))
                        && mi.Menu.SiteID == siteID
                        && item.Active
                        select item;

            return await query.ToListAsync();
        }
```

### The issue
if the left side of an or expression is true then the right side should not be evaluated in the where clause.
This query:
from c in db.customers where (true || c.id == 999) select c
should generate this sql
select * from customers

If you are seeing an exception, include the full exceptions details (message and stack trace).
An exception was thrown while attempting to evaluate the LINQ query parameter expression 'value(Blog.Services.ContentItemService+<>c__DisplayClass3_0).dateFilter.Value.Month'.
```
Exception message:
An exception was thrown while attempting to evaluate the LINQ query parameter expression 'value(Blog.Services.ContentItemService+<>c__DisplayClass3_0).dateFilter.Value.Month'.

Stack trace:
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.TryExtractParameter(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExtractParameters(Expression query, QueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blog.Services.ContentItemService.<GetContentItems>d__3.MoveNext() in C:\Git\Blog\src\Blog.Services\ContentItemService.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blog.Core.ServiceCallWrapper`1.<TryAsync>d__5`1.MoveNext() in C:\Git\Blog\src\Blog.Core\ServiceClient.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blog.API.Controllers.BlogController.<GetContentItems>d__4.MoveNext() in C:\Git\Blog\src\Blog.API\Controllers\BlogController.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
```

### Further technical details

EF Core version: (found in project.json or packages.config)
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
Operating system: Windows 10
Visual Studio version: (e.g. VS 2013 or n/a) 2015 

Other details about my project setup:

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #5736 
For logical binary expressions, we try to evaluate each child and if it converts to true/false then based on the node type we prune the trees.

### CODE REVIEW

**Comment by smitpatel** [comment]
@anpete @maumar

File: src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 1]
```diff
@@ -230,10 +230,80 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
...
+
+            return binaryExpression.Update(newLeftExpression, binaryExpression.Conversion, newRightExpression);
+        }
+
+        private Expression TryOptimize(Expression expression)
+        {
+            if (_partialEvaluationInfo.IsEvaluatableExpression(expression)
+                && !_queryableTypeInfo.IsAssignableFrom(expression.Type.GetTypeInfo()))
+            {
+                var parameterExpression = TryExtractParameter(expression) as ParameterExpression;
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: I think it would be better to try and call Evaluate directly here so we can avoid the Parameter creation completely.

**Comment by smitpatel** [comment]
Updated

File: src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 2]
```diff
@@ -230,10 +230,66 @@ protected override Expression VisitUnary(UnaryExpression unaryExpression)
...
+            return binaryExpression.Update(newLeftExpression, binaryExpression.Conversion, newRightExpression);
+        }
+
+        private Expression TryOptimize(Expression expression)
+        {
+            if (_partialEvaluationInfo.IsEvaluatableExpression(expression)
+                && !_queryableTypeInfo.IsAssignableFrom(expression.Type.GetTypeInfo()))
+            {
+                string _;
+                var value = Evaluate(expression, out _);
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: Do we need the same Try..Catch as in TryExtractParameter?

**Comment by anpete** [comment]
:shipit:
