### PR TITLE
Generate Unique alias for table names

### LINKED ISSUE #3826: Table alias collision in generated SQL with subquery (MSSQL)
Windows 10, VS 2015, IIS Express, SQL Server Express 2014, EF 7.0.0-rc1-final, ASP.NET 6.0.0-rc1-final

I am seeing incorrect SQL generated with subqueries when the tables involved begin with the same letter.

 Models:
```c#
public class Blog
{
        public int BlogId { get; set; }

        public string Title { get; set; }

        public ICollection<BlogPost> BlogPosts { get; set; }
}
```
```c#
public class BlogPost
{
        public int BlogPostId { get; set; }

        public int BlogId { get; set; }

        public Blog Blog { get; set; }

        public string PostText { get; set; }
}
```
FK setup:
```c#
    modelBuilder.Entity<Blog>().HasMany(b => b.BlogPosts).WithOne(p => p.Blog);
```

Query:
```c#
   _dbContext.Blogs.Where(b => b.BlogPosts.Count == 0).ToList();
```

Generated SQL:
```sql
SELECT [b].[BlogId], [b].[Title]
FROM [Blog] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [BlogPost] AS [b]
    WHERE [b].[BlogId] = [b].[BlogId]
) = 0
```

With test data of 2 blogs, 2 posts for blog 1 and 0 for blog 2, this query incorrectly returns 0 results (should return one result, namely blog 2).  If `BlogPost` in the subquery is aliased to something other than [b] it works fine, e.g.:

```sql
SELECT [b].[BlogId], [b].[Title]
FROM [Blog] AS [b]
WHERE (
    SELECT COUNT(*)
    FROM [BlogPost] AS [bp]
    WHERE [bp].[BlogId] = [b].[BlogId]
) = 0
```

### PR DESCRIPTION
**Pull request by smitpatel**
resolves #3826 
Presently it is code change only. If approaches looks right then I will update SQL generated for tests and add more test to verify this scenario.

### CODE REVIEW

**Comment by smitpatel** [comment]
@anpete @maumar

File: src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs [hunk 1]
```diff
@@ -78,5 +82,35 @@ public virtual SelectExpression FindSelectExpression([NotNull] IQuerySource quer
...
+            if (string.IsNullOrEmpty(currentAlias))
+            {
+                return currentAlias;
+            }
+
+            var uniqueAlias = currentAlias;
+            var counter = 0;
+
+            int _;
+            if (int.TryParse(currentAlias.Substring(1), out _))
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: we could change this to work the same for one letter aliases as well as multi letter aliases, i.e.
currently we have:
a -> a0, a1, a2
bb -> bb0, bb00, bb000

we should aim for 
bb -> bb0, bb1, bb2, bb3

Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: updated.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs [hunk 2]
```diff
@@ -179,7 +179,7 @@ var materializer
 
                         selectExpression.Predicate = oldPredicate;
                         selectExpression.RemoveTable(joinExpression);
-                        selectExpression.AddTable(newJoinExpression);
+                        selectExpression.AddTable(newJoinExpression, false);
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs]: Use named parameter to clarify false here.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs [hunk 3]
```diff
@@ -290,8 +290,9 @@ yield return
         private JoinExpressionBase AdjustJoinExpression(
             SelectExpression selectExpression, JoinExpressionBase joinExpression)
         {
-            var subquery = new SelectExpression(_querySqlGeneratorFactory, joinExpression.Alias);
-            subquery.AddTable(joinExpression.TableExpression);
+            var subquery = new SelectExpression(_querySqlGeneratorFactory, _queryCompilationContext) { Alias = joinExpression.Alias };
+            // Don't create new alias when adding tables to subquery
+            subquery.AddTable(joinExpression.TableExpression, false);
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs]: Named parameter.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs [hunk 4]
```diff
@@ -35,22 +36,28 @@ public class SelectExpression : TableExpressionBase
...
             _querySqlGeneratorFactory = querySqlGeneratorFactory;
+            _queryCompilationContext = queryCompilationContext;
         }
 
         public SelectExpression(
             [NotNull] IQuerySqlGeneratorFactory querySqlGeneratorFactory,
+            [NotNull] RelationalQueryCompilationContext queryCompilationContext,
             [NotNull] string alias)
-            : base(null, Check.NotNull(alias, nameof(alias)))
+            : base(null, null)
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs]: Is a null alias allowed here now?

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs [hunk 5]
```diff
@@ -35,22 +36,28 @@ public class SelectExpression : TableExpressionBase
 
         public virtual Expression Predicate { get; [param: CanBeNull] set; }
 
-        public SelectExpression([NotNull] IQuerySqlGeneratorFactory querySqlGeneratorFactory)
+        public SelectExpression([NotNull] IQuerySqlGeneratorFactory querySqlGeneratorFactory,
+            [NotNull] RelationalQueryCompilationContext queryCompilationContext)
             : base(null, null)
         {
             Check.NotNull(querySqlGeneratorFactory, nameof(querySqlGeneratorFactory));
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs]: queryCompilationContext null check?

File: src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs [hunk 6]
```diff
@@ -78,5 +84,30 @@ public virtual SelectExpression FindSelectExpression([NotNull] IQuerySource quer
                  select selectExpression)
                     .First();
         }
+
+        public virtual string CreateUniqueTableAlias()
+            => CreateUniqueTableAlias(SystemAliasPrefix);
+
+        public virtual string CreateUniqueTableAlias([NotNull] string currentAlias)
+        {
+            Debug.Assert(currentAlias != null);
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: Regular Check.NotNull is fine

File: src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs [hunk 7]
```diff
@@ -78,5 +84,30 @@ public virtual SelectExpression FindSelectExpression([NotNull] IQuerySource quer
...
+
+            if (string.IsNullOrEmpty(currentAlias))
+            {
+                return currentAlias;
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: Never reach here due to assert above.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs [hunk 8]
```diff
@@ -20,6 +22,10 @@ public class RelationalQueryCompilationContext : QueryCompilationContext
         private readonly List<RelationalQueryModelVisitor> _relationalQueryModelVisitors
             = new List<RelationalQueryModelVisitor>();
 
+        private const string SystemAliasPrefix = "t";
+        private Regex NumericEnding = new Regex("[0-9]*$", default(RegexOptions), TimeSpan.FromMilliseconds(1000.0));
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: Lets try and do this without Regex. Use Char.IsNumber while iterating backwards.

File: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs [hunk 9]
```diff
@@ -678,9 +678,9 @@ public override void Join_uses_database_semantics()
             base.Join_uses_database_semantics();
 
             Assert.Equal(
-                @"SELECT [e1].[Id], [e2].[Id], [e1].[NullableIntA], [e2].[NullableIntB]
-FROM [NullSemanticsEntity1] AS [e1]
-INNER JOIN [NullSemanticsEntity2] AS [e2] ON [e1].[NullableIntA] = [e2].[NullableIntB]",
+                @"SELECT [e].[Id], [e0].[Id], [e].[NullableIntA], [e0].[NullableIntB]
```
Comment (anpete) [inline test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs]: It looks like we are losing the behavior of trying to re-use the range variable name. We need to try and preserve this behavior. I.e. Only unique-ify when necessary.

**Comment by smitpatel** [comment]
@anpete - Updated with different approach. I checked few tests to verify that we are preserving user-defined names.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs (hunk 5 above)
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs]: Added check.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs (hunk 4 above)
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs]: null alias is still not allowed. We unique-fy alias before assigning it therefore we don't use it in direct call to base.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs [hunk 10]
```diff
@@ -165,7 +165,7 @@ var predicate
 
             if (predicate != null)
             {
-                var innerSelectExpression = handlerContext.SelectExpressionFactory.Create();
+                var innerSelectExpression = handlerContext.SelectExpressionFactory.Create(handlerContext.QueryModelVisitor.QueryCompilationContext);
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs]: break those long lines into 2 separate ones, we usually do something like:

var innerSelectExpression 
   = handlerContext.SelectExpressionFactory.Create(handlerContext.QueryModelVisitor...)

File: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs [hunk 11]
```diff
@@ -200,9 +200,9 @@ public override void Join_navigation_in_inner_selector_translated_to_subquery()
                 @"SELECT [e2].[Id], [e1].[Id]
 FROM [Level2] AS [e2]
 INNER JOIN [Level1] AS [e1] ON [e2].[Id] = (
-    SELECT TOP(1) [subQuery0].[Id]
-    FROM [Level2] AS [subQuery0]
-    WHERE [subQuery0].[Level1_Optional_Id] = [e1].[Id]
+    SELECT TOP(1) [subQuery00].[Id]
```
Comment (maumar) [inline test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs]: we can probably change the base generated name from "subquery0" to "subquery", since it's being uniquefied anyway

File: src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs [hunk 12]
```diff
@@ -78,5 +84,36 @@ public virtual SelectExpression FindSelectExpression([NotNull] IQuerySource quer
...
         }
+
+        public virtual string CreateUniqueTableAlias()
+            => CreateUniqueTableAlias(SystemAliasPrefix);
+
+        public virtual string CreateUniqueTableAlias([NotNull] string currentAlias)
+        {
+            Check.NotNull(currentAlias, nameof(currentAlias));
+
+            if (string.IsNullOrEmpty(currentAlias))
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: Redundant check

Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: Its for Empty Check. if currentAlias is empty then we return empty. Is there any other way to check?

**Comment by smitpatel** [comment]
Updated with feedback. Added some tests.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs [hunk 13]
```diff
@@ -78,5 +84,36 @@ public virtual SelectExpression FindSelectExpression([NotNull] IQuerySource quer
...
         }
+
+        public virtual string CreateUniqueTableAlias()
+            => CreateUniqueTableAlias(SystemAliasPrefix);
+
+        public virtual string CreateUniqueTableAlias([NotNull] string currentAlias)
+        {
+            Check.NotNull(currentAlias, nameof(currentAlias));
+
+            if (string.Equals(currentAlias, ""))
```
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs]: Or, currentAlias.Length == 0

**Comment by anpete** [comment]
@smitpatel Is it just that not all test changes have been reverted from the earlier approach? Because, if not, it looks like we are still unique-fying too much.

**Comment by smitpatel** [comment]
Updated with 1 more change which reduced changes required.
There are mainly 3 reasons for changes occurring
1. We are unique-fying across query model. Therefore if multiple SQL statements are executed aliases will be unique across all. Which was not the case previously.
2. Subquery aliases - During include processing when we generate a subquery for inner join, previously we used same alias as inner table. We are making it unique now.
3. Client Eval - If the query is using client eval then we visit the query model first time using alias names but fails to generate SQL out of it. So when we process query model again for client eval, they will use different aliases.

Most changes in tests look to be consequence of one of the above. If there is any particular test which seems to be unique-fy extra then point me to it and I will investigate it.

**Comment by smitpatel** [comment]
Update to above:
4. Subquery depth - Previously we used t + subquery depth as alias so that push down subquery gets different alias, now we are unique-fying it so we don't use depth anymore. Which changes it to start from `t` instead of `t0` as before.

**Comment by anpete** [comment]
@smitpatel Thanks for the clear explanation. 1,2 & 4 are OK. Can you see if there is any easy fix to 3? Otherwise :shipit:

**Comment by smitpatel** [comment]
For point 3 I tried looking into avoiding it. But we traverse the queryModel 2 times and both generate different `SelectExpression`. And we don't have any way to know what initiated QueryModelVisitor. The only way to do it without changing a lot of things in background would be to remove all generated aliases if client eval starts but it can have side-effects. So I did not attempt that way.
