### PR TITLE
Query: Make GroupJoinInclude in compiled query thread safe

### LINKED ISSUE #5456: Threading Related Crash: NullReferenceException in SimpleNullableDependentKeyValueFactory
I am getting random crash when getting the list but not sure why.

```
        [HttpGet]
        public async Task<List<BookingTimeSlotViewModel>> Get(DateTime start, DateTime end) // need period
        {
            User user = await GetCurrentUser();
            
            // get booking slots with booking detail
            IQueryable<BookingTimeSlot> slots;
            if (await IsAmbassadorManager()) {
                slots = _rosterRepository.GetBookingSlotForManagerBetween(user, start, end);
            } else {
                slots = _rosterRepository.GetBookingSlotForUserBetween(user, start, end);
            }

            return _mapper.Map<List<BookingTimeSlot>, List<BookingTimeSlotViewModel>>(await slots.ToListAsync()); // <<<<<<<<<< CRASH HERE
        }
        
// repository
        public IQueryable<BookingTimeSlot> GetBookingSlotForUserBetween(User user, DateTime start, DateTime end)
        {
            return GetBookingSlotBetween(start, end).Where(s => s.Booking.Outlet.Supervisor == user);
        }
        
        public IQueryable<BookingTimeSlot> GetBookingSlotBetween(DateTime start, DateTime end)
        {
            return _context.BookingTimeSlots
                .Include(s => s.Booking.Outlet)
                .Include(s => s.Rosters)
                .Where(s => s.StartDate <= end && (s.EndDate >= start || (s.Repeat == true && s.RepeatUntil >= start)));
        }
```

Here is the exception log:

```

---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
at lambda_method(Closure , InternalEntityEntry )
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimpleNullableDependentKeyValueFactory`1.TryCreateFromCurrentValues(InternalEntityEntry entry, TKey& key)
at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.CreateIncludeKeyComparer(INavigation navigation, InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCore(Object entity, INavigation navigation)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncGroupJoinInclude.<IncludeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncGroupJoinInclude.<IncludeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.GroupJoinAsyncEnumerable`4.GroupJoinAsyncEnumerator.<MoveNext>d__6.MoveNext()
--- End of inner exception stack trace ---
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
at lambda_method(Closure , InternalEntityEntry )
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimpleNullableDependentKeyValueFactory`1.TryCreateFromCurrentValues(InternalEntityEntry entry, TKey& key)
at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.CreateIncludeKeyComparer(INavigation navigation, InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCore(Object entity, INavigation navigation)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncGroupJoinInclude.<IncludeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncGroupJoinInclude.<IncludeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.GroupJoinAsyncEnumerable`4.GroupJoinAsyncEnumerator.<MoveNext>d__6.MoveNext()
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
at lambda_method(Closure , InternalEntityEntry )
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimpleNullableDependentKeyValueFactory`1.TryCreateFromCurrentValues(InternalEntityEntry entry, TKey& key)
at Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap`1.CreateIncludeKeyComparer(INavigation navigation, InternalEntityEntry entry)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCore(Object entity, INavigation navigation)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncGroupJoinInclude.<IncludeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncGroupJoinInclude.<IncludeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.GroupJoinAsyncEnumerable`4.GroupJoinAsyncEnumerator.<MoveNext>d__6.MoveNext()<---
<---
<---
<---
<---
<---
```

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #5456 
 Issue:  `GroupJoinInclude`  in compiled query has querycontext as field which is initialized while iterating query. If the same query is ran from different thread and uses the cached entry then the querycontext in  `GroupJoinInclude`  gets changed. Which means only 1 query will have correct context, rest of them will be using incorrect data hence causing exception.
 Solution: Make  `GroupJoinInclude`  immutable and use different data structure which is context based for each query.
 Same applies to async case.

### CODE REVIEW

File: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs [hunk 1]
```diff
@@ -1151,6 +1151,84 @@ public class Child3101
...
+        [Fact]
+        public virtual void Repro5456_include_group_join_is_per_query_context_async()
+        {
+            CreateDatabase5456();
+
+            Parallel.For(0, 10, async i =>
+            {
+                using (var ctx = new MyContext5456())
+                {
+                    var result = await ctx.Posts.Where(x => x.Blog.Id > 1).Include(x => x.Blog).ToListAsync();
```
Comment (maumar) [inline test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs]: add tests for more than 1 include

File: test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs [hunk 2]
```diff
@@ -331,6 +332,78 @@ public class Child3101
...
+        private void Seed5456(MyContext5456 context)
+        {
+            for (var i = 0; i < 100; i++)
+            {
+                context.Add(
+                    new Blog5456
+                    {
+                        Posts = new List<Post5456>
+                        {
+                                    new Post5456(),
```
Comment (maumar) [inline test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs]: nit: formatting

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs [hunk 3]
```diff
@@ -59,55 +57,111 @@ public virtual void SetPrevious([NotNull] AsyncGroupJoinInclude previous)
...
+            return asyncGroupJoinIncludeContext;
         }
 
         /// <summary>
-        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used 
+        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
         ///     directly from your code. This API may change or be removed in future releases.
         /// </summary>
-        public virtual void Dispose()
+        public class AsyncGroupJoinIncludeContext : IDisposable
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: this is a breaking change to a public surface: IQueryMethodProvider.GroupJoinIncludeType

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs [hunk 4]
```diff
@@ -59,55 +57,111 @@ public virtual void SetPrevious([NotNull] AsyncGroupJoinInclude previous)
...
+            ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
+            ///     directly from your code. This API may change or be removed in future releases.
+            /// </summary>
+            public virtual void Dispose()
+            {
+                if (_queryContext != null)
+                {
+                    _previous?.Dispose();
+
+                    foreach (var relatedEntitiesLoader in _relatedEntitiesLoaders)
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: _relatedEntityLoaders are shared between all GroupJoinInclude instances - would that be a problem when disposing asynchronously?

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs (hunk 3 above)
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: Yeah, we can just make it a no-op. @divega Can we obsolete this?

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs (hunk 4 above)
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: They aren't shared I believe. The factories are shared.

File: test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs [hunk 5]
```diff
@@ -331,6 +332,78 @@ public class Child3101
             public string Name { get; set; }
         }
 
+        [Fact]
+        public virtual void Repro5456_include_group_join_is_per_query_context()
```
Comment (anpete) [inline test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs]: Can you do the test against Northwind in the shared style?

File: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs (hunk 1 above)
Comment (smitpatel) [inline test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs]: Added.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs (hunk 3 above)
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: Added no-op Dispose methods.

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs (hunk 4 above)
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: @maumar - I added test with multiple includes and multi level includes both are working fine. Any other way to verify that there is no problem?

Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs]: @smitpatel we should be good as far as tests are concerned
