### PR TITLE
Query: Fix #5179: Select Where Navigation returns wrong results on re…

### LINKED ISSUE #5179: Query: Select Where Navigation returns wrong results on relational providers
The existing test in `QueryNavigationsTestBase` returns the correct number of results but incorrect values on relational providers.

```cs
        [ConditionalFact]
        public virtual void Select_Where_Navigation()
        {
            using (var context = CreateContext())
            {
                var orders
                    = (from o in context.Set<Order>()
                       where o.Customer.City == "Seattle"
                       select o).ToList();

                Assert.Equal(14, orders.Count);
            }
        }
```

The list of orders contains 14 references to the same order (10904 on SqlServer, 10269 on Sqlite) instead of the expected results for the query. Results appear to be correct on the InMemory provider.

### PR DESCRIPTION
**Pull request by anpete**
…lational providers

Fixed streaming relational GroupJoin operator to correctly re-group on outer element change.

Also fixed some places where we were failing to flow cancellation tokens.

### CODE REVIEW

**Comment by anpete** [comment]
cc @divega @maumar

File: src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs [hunk 1]
```diff
@@ -89,5 +89,28 @@ public ValueBuffer WithOffset(int offset)
         }
 
         public bool IsEmpty => _values == null;
+
+        public override bool Equals(object obj)
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs]: don't you need similar thing for CompositeShaper?

File: src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs [hunk 2]
```diff
@@ -4331,6 +4331,16 @@ public virtual void GroupJoin_simple2()
                 from o in orders
                 select c);
         }
+        
+        [ConditionalFact]
+        public virtual void GroupJoin_simple3()
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs]: Might want to incorporate tests added in https://github.com/aspnet/EntityFramework/pull/5200, specifically files: QueryNavigationsTestBase, NorthwindData, QueryNavigationsSqlServerTest - there were a few scenarios returning wrong results that were caught by the overhaul

Comment (anpete) [inline src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs]: See my comment on the PR

Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs]: Sounds good, will add the tests separately once your fix is in

File: src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs (hunk 1 above)
Comment (anpete) [inline src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs]: This is ValueBuffer, not Shaper (if that's what you meant) :smile:

Comment (maumar) [inline src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs]: nevermind, default comparer for TransparentIdentifier should handle it just fine

**Comment by maumar** [comment]
:shipit:

File: src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs (hunk 1 above)
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore/Storage/ValueBuffer.cs]: I meant the result of CompositeShaper.Shape - TransparentIdentifier, but it's default comparison should work since its a struct
