### PR TITLE
Avoid infinite recursion in InversePropertyAttributeConvention

### LINKED ISSUE #7057: StackOverflowException with InversePropertyAttribute on 1.1.0
Reported over email...

> I build a taxi service app with backend on ASP.NET Core.
In order to use latest SignalR I switched all package references to 1.2.0-* as it is defined in a SignalR repository. But as I try to perform any request to a database I receive StackOverflowException

I have the repro project for this (it couldn't be shared publically), so I can give it to whoever investigates.

Attaching stack trace as it is too big to add inline [StackTrace.txt](https://github.com/aspnet/EntityFramework/files/600818/StackTrace.txt)

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #7057

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@smitpatel Could you take a look?

File: src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs [hunk 1]
```diff
@@ -122,7 +112,7 @@ public class InversePropertyAttributeConvention : NavigationAttributeEntityTypeC
                     var fk = existingInverse.ForeignKey;
                     if (fk.GetConfigurationSource() == ConfigurationSource.DataAnnotation)
                     {
-                        fk.DeclaringEntityType.Builder.RemoveForeignKey(fk, ConfigurationSource.DataAnnotation);
+                        fk.DeclaringEntityType.Builder.RemoveForeignKey(fk, ConfigurationSource.DataAnnotation, runConventions: false);
```
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: Don't we have to run conventions at some point?

Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: Updated to still run the conventions.

File: src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs [hunk 2]
```diff
@@ -194,11 +188,44 @@ public class InversePropertyAttributeConvention : NavigationAttributeEntityTypeC
...
+                    var baseNavigationPropertyInfo = newBaseType.ClrType.GetRuntimeProperties().First(p => p.Name == navigationPropertyInfo.Name);
+                    if (!newBaseType.Builder.CanAddOrReplaceNavigation(baseNavigationPropertyInfo.Name, ConfigurationSource.DataAnnotation))
+                    {
+                        return true;
+                    }
+
+                    var targetEntityType = targetEntityTypeBuilder.Metadata;
+                    var inverseNavigations = GetInverseNavigations(targetEntityType);
+                    var inverseNavigationPropertyInfo = inverseNavigations
+                        .SingleOrDefault(k => k.Value.Any(i => i.Item1 == navigationPropertyInfo && i.Item2 == entityClrType)).Key;
```
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: Is this call safe? At max only 1 match?

Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: Yes, we ensure this in `AddInverseNavigation`

File: src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs [hunk 3]
```diff
@@ -194,11 +188,44 @@ public class InversePropertyAttributeConvention : NavigationAttributeEntityTypeC
...
+                        if (inverseAttributeNavigationPairs.All(i => i.Item1 == baseNavigationPropertyInfo && i.Item2 == newBaseType.ClrType))
+                        {
+                            if (newBaseType.FindIgnoredMemberConfigurationSource(navigationPropertyInfo.Name) == ConfigurationSource.DataAnnotation)
+                            {
+                                newBaseType.Unignore(navigationPropertyInfo.Name);
+                            }
+
+                            if (targetEntityType.FindIgnoredMemberConfigurationSource(inverseNavigationPropertyInfo.Name) == ConfigurationSource.DataAnnotation)
+                            {
+                                targetEntityType.Unignore(navigationPropertyInfo.Name);
```
Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: `inverseNavigationPropertyInfo.Name`?

Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: nice catch

Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: Another question, since we are not un-ignoring `baseNavigationPropertyInfo` does `ConfigureInverseNavigation` will take care of it?

Comment (AndriySvyryd) [inline src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs]: It will if it adds that navigation

**Comment by smitpatel** [comment]
:shipit:

**Comment by AndriySvyryd** [comment]
@smitpatel Unfortunately ignoring ambiguous navigations can make other ambiguous navigations erroneously unambiguous, so now I changed `RelationshipDiscoveryConvention` instead to use the ambiguity information set by `InversePropertyAttributeConvention`
