### PR TITLE
Query: Handle | and & operator for boolean values properly

### LINKED ISSUE #5930: Query: | and & operators fail
After I migrated from '1.0.0-rc3-21052' to '1.0.0' I found that the following code fails:
```
_context.Set<Event>()
    .Where(r => r.EventNo == "1" | r.EventNo == "2")
    .ToList();

// this code also fails:
_context.Set<Event>()
    .Where(r => r.EventNo == "1" & r.EventNo == "2")
    .ToList();
```
however this code still works fine:
```
_context.Set<Event>()
    .Where(r => r.EventNo == "1" || r.EventNo == "2")
    .ToList();

_context.Set<Event>()
    .Where(r => r.EventNo == "1" && r.EventNo == "2")
    .ToList();
```
I cannot use the last one as temporary workaround, because failed code in 3rd party library.

Output:
```
Compiling query model: 'from Event r in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[EventManager.DataModel.Entities.Event]) where (([r].EventNo == "1") Or ([r].EventNo == "2")) select [r]'
Optimized query model: 'from Event r in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[EventManager.DataModel.Entities.Event]) where (([r].EventNo == "1") Or ([r].EventNo == "2")) select [r]'
TRACKED: True
(QueryContext queryContext) => IEnumerable<Event> _ShapedQuery(
    queryContext: queryContext, 
    shaperCommandContext: SelectExpression: 
        SELECT [r].[ID], [r].[ActualCosts], [r].[Comments], [r].[CompanyID], [r].[CostCenterID], [r].[CreationDateTime], [r].[CreationUser], [r].[CreationUserID], [r].[DepartmentID], [r].[EventNo], [r].[EventTypeVersionID], [r].[FinishDate], [r].[IsAssignAttendeesIndividuallyActual], [r].[IsAssignAttendeesIndividuallyPlanned], [r].[IsBookingSuggestionActualPhase], [r].[IsCancelled], [r].[IsClosed], [r].[IsClosing], [r].[IsCopyAndCancelChildEvent], [r].[IsDeprecated], [r].[IsInActualPhase], [r].[LastChangeDateTime], [r].[LastChangeUserID], [r].[LastModificationDateTime], [r].[LastModificationUser], [r].[Name], [r].[PlannedCosts], [r].[ProjectNumber], [r].[Reason], [r].[RepresenterUserID], [r].[SourceID], [r].[StartDate], [r].[StatusID], [r].[TaxationDate], [r].[VipLoungeDurationDateID], [r].[WasUpdated]
        FROM [Event] AS [r]
        WHERE (([r].[EventNo] = N'1') | ([r].[EventNo] = N'2')) = 1
    , 
    shaper: UnbufferedEntityShaper<Event>
)

Opening connection to database 'XXXXXX' on server 'SQL01'.
Executed DbCommand (32ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [r].[ID], [r].[ActualCosts], [r].[Comments], [r].[CompanyID], [r].[CostCenterID], [r].[CreationDateTime], [r].[CreationUser], [r].[CreationUserID], [r].[DepartmentID], [r].[EventNo], [r].[EventTypeVersionID], [r].[FinishDate], [r].[IsAssignAttendeesIndividuallyActual], [r].[IsAssignAttendeesIndividuallyPlanned], [r].[IsBookingSuggestionActualPhase], [r].[IsCancelled], [r].[IsClosed], [r].[IsClosing], [r].[IsCopyAndCancelChildEvent], [r].[IsDeprecated], [r].[IsInActualPhase], [r].[LastChangeDateTime], [r].[LastChangeUserID], [r].[LastModificationDateTime], [r].[LastModificationUser], [r].[Name], [r].[PlannedCosts], [r].[ProjectNumber], [r].[Reason], [r].[RepresenterUserID], [r].[SourceID], [r].[StartDate], [r].[StatusID], [r].[TaxationDate], [r].[VipLoungeDurationDateID], [r].[WasUpdated]
FROM [Event] AS [r]
WHERE (([r].[EventNo] = N'1') | ([r].[EventNo] = N'2')) = 1

An exception occurred in the database while iterating the results of a query.
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '|'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
ClientConnectionId:3fa56329-072c-46b4-89f1-982d9c5ccaf6
Error Number:102,State:1,Class:15
```

### Further technical details

EF Core version: 1.0.0
Operating system: Windows 8.1
Visual Studio version: 2015 Update 3

### PR DESCRIPTION
**Pull request by smitpatel**
Fixes #5930 
Difference between logical and bitwise operators is, logical operators can short-circuit. In order to prevent short-circuiting and also producing a valid query, converted the Boolean conditions to values.

### CODE REVIEW

File: src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 1]
```diff
@@ -1619,7 +1619,9 @@ protected override Expression VisitBinary(BinaryExpression expression)
             {
                 if (_isSearchCondition)
                 {
-                    if (expression.IsComparisonOperation())
+                    if (expression.IsComparisonOperation()
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: make this also work for non-search condition cases, e.g. in projection (and add corresponding test)

Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: updated.

File: src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs [hunk 2]
```diff
@@ -5732,30 +5732,59 @@ public virtual void Random_next_is_not_funcletized_6()
...
+        {
+            AssertQuery<Order>(
+                os => os.Select(o => o.Customer.City + " " + o.Customer.City));
+        }
+
+        [ConditionalFact]
+        public virtual void Bitwise_or_with_boolean_operators_in_predicate()
+        {
+            AssertQuery<Customer>(cs =>
+                cs.Where(c => c.CustomerID == "ALFKI" | c.CustomerID == "ANATR"),
```
Comment (maumar) [inline src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs]: maybe also add 3 conditions? c.Foo == "A" | c.Foo == "B" | c.Foo == "C", :shipit:  otherwise

Comment (smitpatel) [inline src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs]: Added with 3 ORs and mixed.
