### PR TITLE
Boolean in select

### LINKED ISSUE #649: Query: support conditional expressions
E.g. db.Products.Select(p => new {p.Name, IsExpensive = p.Price >  100});

### LINKED ISSUE #3618: Invalid SQL when projection includes a comparison to a Nullable type
int? selectedId = null;

    var results = await DbContext.Departments
        .Select(x => new {Selected = x.Id == selectedId})
        .ToListAsync();

generates this SQL:

    exec sp_executesql N'SELECT [x].[Id] = @__selectedId_0
    FROM [Department] AS [x]',N'@__selectedId_0 int',@__selectedId_0=NULL

This looks to be similar to https://github.com/aspnet/EntityFramework/issues/2450 (apologies if it is a duplicate).

### LINKED ISSUE #3703: Incorrect syntax generated for select new { bool }
Beta8 / SQL Server 2014
Database model:

```
public class Blog
{
        public int BlogId { get; set; }
        public string Url { get; set; }
        public bool IsHipster { get; set; } // <=
        public List<Post> Posts { get; set; }
}
```

Repository model:

```
public class RepositoryBlog
{
        public int BlogId { get; set; }
        public string Url { get; set; }
        public bool IsHippy { get; set; } // <=
        public List<Post> Posts { get; set; }
}
```

Query 1:

```
List<RepositoryBlog> x = (from b in db.Blogs
	select new RepositoryBlog
	{
		BlogId = b.BlogId,
		IsHippy = !b.IsHipster, // Note negation
		Url = b.Url
	}).ToList();
```

Generated SQL:

```
SELECT [b].[BlogId], [b].[IsHipster] = 0, [b].[Url]
FROM [Blog] AS [b]
```

SQL Server error:

```
Incorrect syntax near '='.
```

Query 2:

```
List<RepositoryBlog> x = (from b in db.Blogs
  select new RepositoryBlog
  {
	  BlogId = b.BlogId,
	  IsHippy = b.IsHipster ? false : true, // Attempted workaround
	  Url = b.Url
  }).ToList();
```

Generated SQL:

```
SELECT [b].[BlogId], CASE
    WHEN [b].[IsHipster]
    THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT)
END, [b].[Url]
FROM [Blog] AS [b]
```

SQL Server error:

```
An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.
```

Twice the fun!

### PR DESCRIPTION
**Pull request by smitpatel**
resolves #3703 
Issue: SQL does not allow not operation on Boolean type directly. They must be compared with true or false. Fix is to convert unary operations on Boolean type to comparison operation.
resolves  #3618 
Issue: SQL does not allow comparison operation into projection. They must be wrapped in `Case When Then` block.
Fix: Whenever there is comparison operation into projection, convert it to conditional expression.
If comparison operation is inside conditional expression already then do no convert.
Issue: Comparison follows null semantics.
Implementation: While processing `SelectExpression` process the projection accordingly.
resolves #649 for projections

### CODE REVIEW

File: src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 1]
```diff
@@ -143,7 +143,14 @@ public virtual Expression VisitSelect(SelectExpression selectExpression)
                     _relationalCommandBuilder.Append(", ");
                 }
 
-                VisitJoin(selectExpression.Projection);
+                var comparisonTransformer = new ProjectionComparisonTransformingVisitor();
+                var nullComparisonTransformer = new NullComparisonTransformingVisitor(_parametersValues);
```
Comment (anpete) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: DRY this up with predicate case below.

File: src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 2]
```diff
@@ -143,7 +143,14 @@ public virtual Expression VisitSelect(SelectExpression selectExpression)
                     _relationalCommandBuilder.Append(", ");
                 }
 
-                VisitJoin(selectExpression.Projection);
+                var comparisonTransformer = new ProjectionComparisonTransformingVisitor();
```
Comment (anpete) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: One question: Should this handling be in our base SQL gen vs SQL Server? Is it appropriate for the general case?

File: src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 3]
```diff
@@ -143,7 +143,14 @@ public virtual Expression VisitSelect(SelectExpression selectExpression)
...
+                var nullComparisonTransformer = new NullComparisonTransformingVisitor(_parametersValues);
+                var transformedProjections = selectExpression.Projection
+                    .Select(comparisonTransformer.Visit)
+                    .Select(nullComparisonTransformer.Visit)
+                    .ToList();
+
```
Comment (anpete) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: I'm assuming we do this rewrite as part of SQL gen because it can be dependent on parameter values?

File: src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs (hunk 2 above)
Comment (smitpatel) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: This works on MySQL, looks like SQL server specific issue.

**Comment by smitpatel** [comment]
Updated
Split converting comparison to case block to SqlServer Specific. Null semantics are required for SQLite too so it is in relational.

**Comment by anpete** [comment]
@smitpatel Does this potentially resolve #649?

File: src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 4]
```diff
@@ -1125,7 +1132,7 @@ protected virtual bool TryGenerateBinaryOperator(ExpressionType op, [NotNull] ou
         protected override Exception CreateUnhandledItemException<T>(T unhandledItem, string visitMethod)
             => new NotImplementedException(visitMethod);
 
-        private class NullComparisonTransformingVisitor : RelinqExpressionVisitor
+        protected class NullComparisonTransformingVisitor : RelinqExpressionVisitor
```
Comment (anpete) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: This need to be protected?

File: src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 5]
```diff
@@ -143,7 +145,10 @@ public virtual Expression VisitSelect(SelectExpression selectExpression)
                     _relationalCommandBuilder.Append(", ");
                 }
 
-                VisitJoin(selectExpression.Projection);
+                var transformedProjection = TransformProjection(selectExpression)
```
Comment (anpete) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: Looks good. I think we could make the pattern more consistent by tweaking it slightly: Introduce a method VisitProjection(IReadOnlyList<Expression>). In the base class it would run the null comparison transformer and call VisitJoin. In the SQL Server override it would run the projection comparison transformer and then call base. Do you think that would work?

Comment (smitpatel) [inline src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: Changed it. Looked better pattern as it allows provider to change the way projection is processed.

**Comment by smitpatel** [comment]
#649 is resolved by this at least for projections.

**Comment by anpete** [comment]
:shipit:
