### PR TITLE
Log a warning when a DIET instance is shared.

### LINKED ISSUE #8387: Consider throwing when a DIET instance is shared
At least log a warning as mutating it could lead to unexpected results if the user is not aware it's being shared.
Once we have readonly entities, they can be shared without any issues.

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #8387

### CODE REVIEW

File: src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs [hunk 1]
```diff
@@ -59,6 +59,31 @@ private static string SaveChangesFailed(EventDefinitionBase definition, EventDat
...
+        {
+            var definition = CoreStrings.LogDuplicateDietInstance;
+
+            definition.Log(diagnostics, diet1, diet2);
+
+            if (diagnostics.DiagnosticSource.IsEnabled(definition.EventId.Name))
+            {
+                diagnostics.DiagnosticSource.Write(
+                    definition.EventId.Name,
+                    new
```
Comment (ajcvickers) [inline src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs]: This should be a nominal type, following the pattern of other methods here. Also, consider passing actual IEntityType instances instead of just strings.
